### ISSUE TITLE
Allow <subst> in <line> please

### ISSUE THREAD

**Issue by lb42** [TEIC/TEI#1493] opened 2016-08-06 15:05 UTC
The content model for &lt;line> currently permits almost all transcriptional elements, but not &lt;subst>. I suspect this may be for ideological reasons, but if we want to ruthlessly exclude "interpretative" elements  there are several others which ought to be removed as well (e.g. &lt;substJoin>, &lt;supplied> etc). It's certainly hard to justify permitting  &lt;substJoin> but not &lt;subst>!

**Comment by jakub-simek** [comment] 2016-08-18 13:33
I am very much supporting this request. It makes very little sense to me permitting some other potentially interpretative transcriptional elements and forbidding `<subst>` with its very basic semantics. The topic was discussed in 2013 in the [TEI forum](https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1304&L=TEI-L&P=R10386&1=TEI-L&9=A&J=on&d=No+Match%3BMatch%3BMatches&z=4) (thanks to Philipp Vanscheidt for the hint!).   There it was recommended to use `<mod type="subst">` as a workaround (this use is even mentioned in the Guidelines as example for `<mod>` but not explicitly in the context of "embedded transcription" . But is it really necessary to look for such workarounds when the proper element <subst> could be used? If it was permitted, everybody could still decide if they want to use this slightly interpretative layer or not.

**Comment by gerritbruening** [comment] 2016-08-18 13:42
This is somehow connected to https://github.com/TEIC/TEI/issues/1427, isn't it?

I never understood the rigorous content model of `<line>`, but it was tenaciously defended in the past. I agree that it should be the users themselves who decide how rigorous or pure they want their encoding to be.

**Comment by jamescummings** [comment] 2016-08-19 14:01
I agree with @lb42's  initial request but I suspect not in the way @jakub-simek would like. The answer is to *remove* `<substJoin>` and friends from the content model of `<line>` though, not permit even more interpretative elements to be used inside `<sourceDoc>` which is meant to be for non-interpretative transcriptions.  I remember when we were having the discussion about including `<add>` and `<del>` I warned that this might be a slippery slope and we should restrict it as much as possible. (I'd rather just have `<mod>`.) If we are going to have something for non-interpretative transcriptions then it seems blatantly ridiculous to me to inch by inch allow in more and more interpretative elements in it.  If I had my way we would remove all of the "slightly interpretative" elements from it.

@jakub-simek: If you want to use things like `<subst>`, as you say the 'proper' element then surely you aren't doing the type of transcription that `<sourceDoc>` was intended for and you should do your transcription in `<text>`?

**Comment by lb42** [comment] 2016-08-19 14:47
Just to note that &lt;line> is also permitted as a descendant of  &lt;facsimile>, which is agnostic about the grand text/document dichotomy. So you might well want to permit some interpretive elements in that case.

**Comment by gerritbruening** [comment] 2016-08-24 11:47
In the Faustedition we have indeed refrained from using `<add>` and `<del>` within `<line>`, so I honour your rigourism, @jamescummings. However, I doubt there are more projects who have struggled for such purity. Most users will try to smuggle in all the information they consider relevant (be it interpretive or not).  

It might well be true that many of these users would be better off with the good old

    <p>Text text text
    <lb/>text text text 
    <lb/>text text text
    </p>

instead of

    <line>Text text text</line>
    <line>text text text</line>
    <line>text text text</line>

But the current version of chapter eleven invites has a slight tendency to invite users to use `<sourceDoc>` instead of `<text>`.

**Comment by lb42** [comment] 2016-09-26 15:36
Agreed to fix this by removing model.ppart.transcriptional and model.segLike from content model  and adding the following explicitly to model.linePart : add dama ge del handshift mod redo restore retrace unclear undo c pc seg w

**Comment by emylonas** [comment] 2016-11-17 01:28
removed  `model.ppart.transcriptional` and `model.segLike` from `model.linePart` 
added `add` `damage` `del` `handshift`  `mod` `redo` `restore` `retrace` `unclear` `undo` `c` `pc` `seg` `w` to  `model.linePart`

**Comment by emylonas** [comment] 2016-11-17 01:37
Fixed with commit https://github.com/TEIC/TEI/commit/072f95b716b8b40b1f88dc2148e2834cdcd57c1c

**Closed by emylonas** 2016-11-17 01:37 UTC
Labels: Status: Needs Discussion, Type: Bug
