### ISSUE TITLE
TEI Website's not working

### ISSUE THREAD

**Issue by albarranelena** [TEIC/TEI#1855] opened 2019-02-12 16:54 UTC
Hello,

Today I tried to apply some changes to an ODD using ROMA, and I found a 404 server error message, and a reference to nginx.org  instead. [http://tei-c.org/](url). Neither ROMA, or any link associated with the TEI website is working!

Thanks for your attention!

Best regards,

Elena Albarrán Fernández

**Comment by TomazErjavec** [comment] 2019-02-12 17:08
Yes, since Saturday, it's also been posted on tei-l. Unfortunatelly without any indication when it will be up again. We are all suffering :)

**Comment by peterstadler** [comment] 2019-02-12 19:28
There is a severe failure in the ADHO infrastructure and several DH communities are affected.
While the infrastructure is still being rebuild, we (the TEI) managed to provide temporary services at

* https://roma2.tei-c.org for Roma
* https://oxgarage2.tei-c.org for OxGarage
* https://tei-c.dhinstitute.ca for the website
* https://jenkins.tei-c.org/job/TEIP5/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/index.html for the Guidelines

Sorry for the inconvenience!

**Comment by albarranelena** [comment] 2019-02-13 09:42
Thank you, Peter!

I now recall a mail sent by the TEI warning us, but I couldn't find it anymore in my mailbox. This might work, for now!

**Comment by EsGeh** [comment] 2019-02-19 10:44
The way I see it, we need the "Vault" to be able to use the stylsheets, e.g. to compile ODDs.
One central resource is the [p5subset.xml](http://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml)
Is there an alternative source for this file?
It seems it's not in the github repositories, right? Can it be compiled from the repositories somehow?
Does anyone have a backup he can share?

Any hints are welcome

**Comment by sydb** [comment] 2019-02-19 11:40
Yes, p5subset.xml is compiled (as it were) from the source files in this repository using the styesheets in the [Stylesheets](http://github.com/TEIC/Stylesheets/) repository. It is not hard, but neither is it trivial to build p5subset.xml. I will try to post instructions here shortly. In the meantime feel free to download [this copy](http://paramedic.wwp.northeastern.edu/~syd/temp/TEI/p5subset.xml).

**Comment by sydb** [comment] 2019-02-19 11:52
Worth noting what “p5subset.xml” **is**. It is essentially just a copy of P5 (which, of course, is written in TEI) with all of the prose chapters stripped out, leaving only the definition of the TEI schema language (itself written in ODD) left. The entirety of P5 is ~6.4 MiB, and the subset is ~3.7 MiB.

**Comment by lb42** [comment] 2019-02-19 12:07
And may I also reiterate my view that "p5subset" is a really daft name for it? It is a subset in the sense that it doesn't contain the text, true, but it is most likely to be used when people are compiling an ODD -- in which context they are highly probably defining a P5 "subset" in the much more appropriate sense of "providing a subset of the elements defined in the full TEI P5 (err, "subset")" Let's rename it "p5library" or "p5declarations" or something less confusing!

Having got that off my chest, I note that the HTML files compiled from the current Guidelines *are* available in a Github repository https://github.com/TEIC/teic.github.io : why shouldn't this file be available from the same place?

**Comment by lb42** [comment] 2019-02-19 12:12
And just to pre-empt Syd: if you are running unix, generating the p5subset file is a simple matter of getting up to date local copies of the Guidelines sources and the stylesheets, and then running "make". Well, OK, you need a few other things installed like saxon, but you have those already, right?

**Comment by TomazErjavec** [comment] 2019-02-19 12:31
> Worth noting what “p5subset.xml” **is**. It is essentially just a copy of P5 (which, of course, is written in TEI) with all of the prose chapters stripped out, leaving only the definition of the TEI schema language (itself written in ODD) left. The entirety of P5 is ~6.4 MiB, and the subset is ~3.7 MiB.

Thank's @sydb for explaining this - I've been wondering what it is for ages. But now that I know, and noting that it is not even half smaller than the complete P5, I wonder if it is worth the hassle, rather than just using the complete P5.

**Comment by lb42** [comment] 2019-02-19 12:37
@TomazErjavec The P5 source contains shortcuts like `<specGrpRef>`  and similar which are expanded and made explicit in the "p5subset" --  think of it as a compiled library. An ODD processor can be simpler (a bit) as a consequence.

**Comment by EsGeh** [comment] 2019-02-19 14:01
thanks a lot for the explanations. All very helpful!

**Comment by sydb** [comment] 2019-02-19 16:20
BTW, not sure why I went about putting up a copy of p5subset.xml, since it is readily available in the P5 distributions, available both here [on GitHub](https://github.com/TEIC/TEI/releases/tag/P5_Release_3.5.0) and also from [Sourceforge](https://sourceforge.net/projects/tei/).

So ignore my [recent post](#issuecomment-465100199) and just grab the released P5. (p5subset.xml is in the directory /xml/tei/odd/.)

**Comment by lb42** [comment] 2019-02-19 16:49
Doh! Of course... you probably forgot (like me) that the Release repo 
isn't part of the "dev" thing my github points to by default ...

**Comment by peterstadler** [comment] 2019-02-19 19:25
Yet another location to find the current `p5subset.xml` (and friends) is Mr. Jenkins, see https://jenkins.tei-c.org/job/TEIP5/lastSuccessfulBuild/artifact/P5/release/xml/tei/odd/

**Comment by sydb** [comment] 2019-02-19 20:13
@lb42: Worse, I also forgot p5subset.xml was in there!

@peterstadler: Really? I thought that version was built from the development branch, not the released P5 (not that there is all that much difference, but still…)

**Comment by EsGeh** [comment] 2019-02-20 11:53
Maybe it would be helpful to have hints in the TEI docs or maybe the github README on the following topics

- where to find the mentioned [releases](https://github.com/TEIC/TEI/releases/tag/P5_Release_3.5.0)
- how to build the release from the sources. (There is a makefile, ok. It doesn't work out of the box though (Dependencies?). Also, what does it do, actually?)

In case it's already there, it might be worth noting that it's not quite easy to find these informations.
It would also interesting to have an overview on the resources, scripts, the directory structure, etc.
This even more applies to the TEI/Stylesheets repository.

I have been developing some stylesheets to work with odd's on my own.
Having more introductory informations how to work with the source repositories might help to prevent redundant work and simplify  sharing improvements.

**Comment by lb42** [comment] 2019-02-21 10:49
For information on how to edit and build the Guidelines, the best 
starting point is http://teic.github.io/TCW/tcw20.html.  There is useful 
information about how to build the website and releases using Docker at 
http://teic.github.io/TCW/testing_and_building.html
and there is also quite a lot of documentation about the Stylesheets 
from a user perspective, but I agree that there isn't any documentation 
as such for the Makefile, and there probably should be.

Great to learn that you are developing your own ODD processor! The TEI 
Council will, I know, be delighted to share its expertise with you!

**Comment by TinaRussell** [comment] 2019-03-06 02:16
What’s up with the DTDs? For instance, the XML files at https://github.com/PerseusDL/lexica use a doctype declaration pointing to http://www.tei-c.org/Guidelines/DTD/tei2.dtd, which gets me a 404. I did find the same file (I think?) at http://www.tei-c.org/Vault/P4/xml/schema/dtd/tei2.dtd, but it’s served with the MIME type “application/octet-stream”, which seems to confuse XML parsers. (Even if I change the URLs myself in my local copy of the XML files, from the broken “Guidelines” URL to the less-broken “Vault” URL, TXM still tells me “The markup declarations contained or pointed to by the document type declaration must be well-formed” and refuses to parse the files.)
Is this due to the server problems? That’s fine if so, I just want to know what the problem is and if there are any workarounds I can use in the meantime. Thanks!

**Comment by peterstadler** [comment] 2019-03-06 08:50
@TinaRussell yes, that's still not really useable, I see.
What makes things worse is that the TEI website was not very well structured (IMHO) and files are scattered at different (and sometimes duplicate) locations. Still, I'd say the recommended way for referencing files is at the vault and I'm pretty sure that http://www.tei-c.org/Vault/P4/xml/schema/dtd/tei2.dtd is indeed the file you're looking for. 

I'll get in contact with our webmaster to set the MIME type properly.

**Comment by peterstadler** [comment] 2019-03-06 09:23
@TinaRussell  BTW, there is a mirror of the vault at https://vault.tei-c.de including the [DTD](https://vault.tei-c.de/P4/xml/schema/dtd/tei2.dtd). I just changed the server config to serve DTDs with MIME type `application/xml-dtd` -- does that help?

**Comment by jdmartin** [comment] 2019-03-06 19:21
Hi All,

@ldmm let me know about the issue, and so I've made changes to the tei-c.org domain in order to address the issue that @TinaRussell raised.  All .dtd files will now be served by nginx as Content-Type: application/xml-dtd.  

Here's some sample output showing this:

![screen shot 2019-03-06 at 11 14 33 am](https://user-images.githubusercontent.com/1966209/53907329-ca9de080-4001-11e9-9dd0-22be536d9040.png)

Hope that helps!  I'm really just a bystander who works with @ldmm, but I'm happy to help where I can. :)

**Comment by TinaRussell** [comment] 2019-03-06 20:57
Ah, yes! I can confirm the change from here. Sadly, TXM still chokes on the same error :confused: BaseX seems to work… unless I tell it to parse DTDs, in which case it gets the same error that TXM does.

…I should add the caveat that I don’t really know what I’m doing :sweat_smile: I originally wanted to put together some tools for Emacs to help me learn Ancient Greek, and I figured I’d start by making something that would show me the LSJ entry for a given Greek word. Of course, the XML files for the LSJ are hefty, so I figured I’d need a specialized external tool to query them and bring back just the section of XML that I need. I chose TXM because it’s open-source, supports the TEI stuff, and has a command-line tool that—I think—doesn’t load up Java like everything else seems to. (Nothing against Java, I just figured something run from Emacs that loads up the JVM is too much bloat… especially since everything related to Greek morphology seems to be written in Python, meaning I’d need to load up a Python interpreter to find dictionary forms of words… but I’m getting ahead of myself.)

So, let me know if there’s a better way to do what I’m doing. :relaxed: I don’t quite know what eventual form my project will take, but that’s why I want to choose the right tools for a strong start.

**Comment by lb42** [comment] 2019-03-06 22:20
If you just want to extract bits out of an existing XML resource like the LSJ you don't need to worry about parsing its DTD.  I'd just zap the DOCTYPE statement from my local copy of the LSJ (assuming that's what you have). Then I'd use something like baseX or eXist to  extract bits from it real fast and pass them to emacs. But maybe I've misunderstood what you;'re doing.

**Comment by TinaRussell** [comment] 2019-03-06 23:43
Yeah, that’s pretty much the idea. I figured it would be better to start with software that’s aware of the TEI-specific properties, simply because I don’t know right now in what direction I’ll take my project. (Like, maybe I’d want to add something to make biographical references clickable and show information about the person in question, or automatically convert Greek words in Beta code to Unicode, etc.; of course, maybe things like that don’t require the DTD either.)

**Comment by hcayless** [comment] 2019-03-07 00:36
Beta code to Unicode does not require a DTD (I have code that does the conversion if you need it). I wonder why the dictionary files are still P4 when all their texts have been converted to P5?

**Comment by TinaRussell** [comment] 2019-03-07 01:20
> Beta code to Unicode does not require a DTD (I have code that does the conversion if you need it).

Yes, please! (I figured some programmatic understanding of TEI XML might be necessary to figure out which regions to convert—i.e. what’s Beta code and what’s just some unusually punctuated Latin letters—but like I said, I don’t necessarily know what I’m doing…)

**Comment by TinaRussell** [comment] 2019-03-08 02:06
BTW, I tried using `xmlstarlet`’s validator to check one of the LSJ XML files against a _local_ copy of `tei2.dtd`:
```
$ xmlstarlet val -d ~/downloads/tei2.dtd grc.lsj.perseus-eng6.xml 
Could not parse DTD /home/tina/downloads/tei2.dtd
grc.lsj.perseus-eng6.xml - invalid
```
Should this be a new bug report? Or should I file one with the Perseus lexica project, asking them to switch to a newer version of the DTD?

**Comment by sydb** [comment] 2019-03-08 02:57
From where did you get that local copy of tei2.dtd? From [the vault](www.tei-c.org/Vault/P4/xml/schema/dtd/tei2.dtd) as @peterstadler mentioned? That DTD is not meant to be used in a stand alone way, but rather as part of a document type declaration that might look something like
~~~~~
<!DOCTYPE TEI.2 PUBLIC "-//TEI P4//DTD Main DTD Driver File//EN" "tei2.dtd" [
    <!ENTITY % TEI.prose 'INCLUDE'>
    <!ENTITY % TEI.XML 'INCLUDE'>
    <!ENTITY % TEI.linking 'INCLUDE'>
]>
~~~~~
In fact in one of those LSJ files you were talking about, it looks like
~~~~~
<!DOCTYPE TEI.2 PUBLIC "-//TEI P4//DTD Main DTD Driver File//EN" "http://www.tei-c.org/Guidelines/DTD/tei2.dtd" [
   <!ENTITY % TEI.XML "INCLUDE">
   <!ENTITY % PersDict PUBLIC "-//Perseus P4//DTD Perseus Dictionaries//EN" "http://www.perseus.tufts.edu/DTD/1.0/PersDict.dtd" >
    %PersDict;
]>
~~~~~
Which means you also need a copy of the PersDict.dtd file. But in any case, in order to get a version of a TEI P4 DTD that could be used with a tool like `xmlstarlet`, you would need to use either [carthage](https://github.com/TEIC/Carthage) or [the Pizza Chef](https://www.tei-c.org/Vault/P4/pizza.html) (a web front-end to `carthage`) to “flatten” the DTD first.

But to be clear, this is all P4, which has not been supported for the past 7 years or so.

**Comment by TinaRussell** [comment] 2019-03-08 17:46
Wow, I’m in over my head :sweat_smile: Thanks for your help!

**Comment by sydb** [comment] 2019-03-08 21:32
That depends a bit, I suppose, on how tall you are. If you’re able to run `xmlstarlet`, you’re doing pretty well IMHO. You might try `xmlstarlet val -E grc.lsj.perseus-eng6.xml ` instead. The -E switch says to read the embedded DTD and use that. If the paths to the external DTD files are correct in the DOCTYPE declaration, there is a good chance it will work. (But I’m not at all sure `xmlstarlet` will read an external DTD like that.)

**Comment by peterstadler** [comment] 2019-07-05 19:45
Closing this since the original issue is resolved; Roma and website are up again

**Closed by peterstadler** 2019-07-05 19:45 UTC
