### ISSUE TITLE
how to specify units of att.coordinated attrs?

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1413] opened 2015-12-15 14:33 UTC
The remarks of `<surface>` say
```xml
<p>The coordinate space defined by this element may be thought of
    as a grid <att>lrx</att> - <att>ulx</att> units wide and
    <att>uly</att> - <att>lry</att> units high. </p>
```
and a footnote in PH says (emphasis added — Markdown isn’t all that bad):

> The coordinate space used here is based on pixels, but _the mapping between **pixels** and **units** in the coordinate space **need not be one-to-one**_; it might be convenient to define a more delicate grid, to enable us to address much smaller parts of the image. This can be done simply by supplying appropriate values for the attributes which define the coordinate space; for example doubling them all would map each pixel to two grid points in the coordinate space.

So I want to develop a set of `<surface>`s and `<zone>`s that use a coordinate space based on millimeters, not pixels; or even 2-for-1 pixels as the footnote mentions. How do I express the fact that my `@lrx` is in mm, not pixels? I have not figured out how. If we do not have such a mechanism, then this bug report is that the mechanism is missing. If I’ve just missed it, then the issue here is that the mechanism should be more prominently mentioned (e.g., in the tagdoc of att.coordinated and in some examples of `<surface>`, `<zone>`, and `<line>`.

**Comment by lb42** [comment] 2015-12-15 15:01
It's not a bug. It's a feature. The coordinate system just specifies the number of cells in the grid on either axis, nothing about their size when printed out or displayed.

**Comment by hcayless** [comment] 2016-02-03 18:29
Right, but @sydb is asking how one might specify what the units in a coordinate system are. I don't think it's unreasonable to want to do so.

**Comment by lb42** [comment] 2016-02-03 19:25
But that's the point. It's a coordinate system. The whole of the space is divided into n parts one way, and m another. The size (and hence the units) of n and m is not relevant, or indeed meaningful. It's like asking what units pi is measured in.

**Comment by lb42** [comment] 2016-02-25 17:29
I'm going to close this now. Reopen if you're still puzzled.

**Closed by lb42** 2016-02-25 17:29 UTC
Labels: Status: Needs Discussion, TEI: Guidelines & Documentation, Type: Bug

**Comment by hcayless** [comment] 2016-02-25 17:34
I remain puzzled (as I always have been) why we have an abstract coordinate
system without the means to map it to real measurements, but I haven't used
it, so I don't have any concrete objections to it either.
