### ISSUE TITLE
attDef datatype namespace error

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1605] opened 2017-03-11 17:19 UTC
This appears to be new since at least last November 2016. I opened three different ODDs, two of which I created for projects in fall 2016 which were fine when I created them. Now I notice new errors flagging the `datatype` child of `attDef`. The error fires when `datatype` contains a `dataRef` child, and the message reads, 
````
datatype content must be in the namespace "
````
That's all. It looks like an incomplete error message. To repair it, I can replace the `dataref` with a Relax NG namespaced element, as in `rng:text` or `rng:integer`. If we enacted a new rule recently that is now requiring a namespaced child of datatype, we need this rule to be better documented, and this error message needs to be fleshed out. 

I know we've talked about issues with defining datatypes, but I'm not seeing any documentation in the Guidelines about it. Can anyone explain what's going on here?

**Comment by lb42** [comment] 2017-03-11 17:31
I've seen this error message before, but I can't remember what causes it. Could you post a bit more of the ODD that causes the problem?  In particular what attributes does the &lt;dataRef> specify and is the tei module included in your schema ?

**Comment by ebeshero** [comment] 2017-03-11 17:42
Well I've got lots of examples from three different files. Yes, I've got ` <moduleRef key="tei"/>` in all three ODDs. Here's an abbreviated example from one of my ODDs, with a nice selection of four dataRef elements which use either `@key` or `@name`. I notice I left a bundle of comments on these last fall because I wasn't confident they were working anyway, but they weren't firing errors in my ODD then: 
````
<schemaSpec ident="EldritchODD" start="TEI teiCorpus" prefix="tei">
    <moduleRef key="tei"/>
[...bunch of other modules...]
    <moduleRef key="analysis" include="w phr cl"/>

  <elementSpec ident="w" module="analysis" mode="change">
            <constraintSpec scheme="isoschematron" ident="synsetFormat">
                  <constraint>
                     <sch:rule context="tei:w/@synset">
                        <sch:assert test="matches(., '^[a-z]+\.[a-z]\.\d{2}$')">
                           When using the attribute @synset on a w element, it must match the wordnet format, like so: "ghost.n.03", "frighten.v.01" , "eldritch.a.01". 
                        </sch:assert>
                     </sch:rule>
                  </constraint>
               </constraintSpec>
            <attList>
               <attDef ident="synset" mode="add" usage="rec">
                  <datatype>
                     <dataRef key="teidata.pattern" restriction="^[a-z]+\.[a-z]\.\d{2}$"/>
                     <!--2016-12-05 ebb: attempting to fix with teidata.pattern instead of data.pattern.
                        2016-12-02 ebb: This doesn't seem to be working on its own, so we added a Schematron constraint to control the content.-->
                  </datatype>
               </attDef>  
               <attDef ident="synsetCount" mode="add" usage="rec">
                  <datatype>
                     <dataRef name="integer"/>
                     <!--2016-12-02 ebb: This doesn't seem to be working on its own, so we added a Schematron constraint to control the content.-->
                  </datatype>
               </attDef>  
            </attList>
         </elementSpec>
````

**Comment by lb42** [comment] 2017-03-11 18:14
Interesting. I cannot reproduce the error you cite, using a very simple ODD containing just the declaration above and the tei module. I suspect that you have a namespace prefix issue.

Note that  the @restriction attribute  won't work with a TEI datatype: you need to apply it to e.g. name="token".  That should be documented more clearly: you can't use @restriction along with @key because key might point to a data spec which already includes a restriction.  The datatype for synsetCount works fine for me.

Here's my sample ODD (which appears to Do The Right Thing)
~~~~
     <schemaSpec ident="myTEI" start="w"
            xmlns:sch="http://purl.oclc.org/dsdl/schematron">
            <moduleRef key="tei"/>
            <elementRef key="w"/>
            
            <elementSpec ident="w" mode="change">
          <constraintSpec scheme="isoschematron" ident="synsetFormat">
                  <constraint>
                     <sch:rule context="tei:w/@synset">
                        <sch:assert test="matches(., '^[a-z]+\.[a-z]\.\d{2}$')">
                           When using the attribute @synset on a w element, it must match the wordnet format, like so: "ghost.n.03", "frighten.v.01" , "eldritch.a.01". 
                        </sch:assert>
                     </sch:rule>
                  </constraint>
               </constraintSpec>
               <attList>
                  <attDef ident="synset" mode="add" usage="rec">
                     <datatype>
                        <dataRef name="token" restriction="^[a-z]+\.[a-z]\.\d{2}$"/>
                        <!--2016-12-05 ebb: attempting to fix with teidata.pattern instead of data.pattern.
                        2016-12-02 ebb: This doesn't seem to be working on its own, so we added a Schematron constraint to control the content.-->
                     </datatype>
                  </attDef>  
                  <attDef ident="synsetCount" mode="add" usage="rec">
                     <datatype>
                        <dataRef name="integer"/>
                        <!--2016-12-02 ebb: This doesn't seem to be working on its own, so we added a Schematron constraint to control the content.-->
                     </datatype>
                  </attDef>  
               </attList>
            </elementSpec>            
      </schemaSpec>
~~~~

**Comment by lb42** [comment] 2017-03-11 18:23
Ah, I've remembered where I saw this message before. It was caused by a bug in the way anyElement is processed and appears if you are validating against tei_all and if you have schematron switched on. I thought this had been fixed, but maybe I was wrong.

**Comment by ebeshero** [comment] 2017-03-11 18:29
@lb42 Thanks for the help with `@restriction`! (Do we have an open ticket on clarifying that?...I can check, but perhaps you're aware of it already...)

As for validation, I'm using tei_odds.rng (the default validator in oXygen):
````
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
````

**Comment by lb42** [comment] 2017-03-11 18:31
Maybe you could email me one of your offending ODDs for further scrutiny?

**Comment by ebeshero** [comment] 2017-03-11 18:35
How about I point to it from its GitHub repo? I'm about to update the Eldritch ODD that I've been sampling here. Hang on a minute. (And thank you for taking a look!)

**Comment by lb42** [comment] 2017-03-11 18:39
An eldritch odd sounds just the thing for a winter evening.... have added https://github.com/TEIC/TEI/issues/1606 for the @restriction problem

**Comment by ebeshero** [comment] 2017-03-11 19:11
@lb42 Here's the Eldritch ODD:
https://github.com/PPH3/Eldritch/tree/master/ODD

**Comment by lb42** [comment] 2017-03-11 20:07
Thanks - I downloaded that and generated RNG and HTML without problem and without changing it in any way; I also used the resulting schema to validate a trivial document. Is your oXygen framework perhaps out of sorts?

**Comment by ebeshero** [comment] 2017-03-11 20:40
@lb42 The ODD works to generate RNG and HTML just fine--it's all functioning properly here, too. The problem I see is that bizarre error on dataRef elements when I open the ODD. I'm on my Linux machine and updated to the current 18.1 oXygen today...I'll try switching computers and see if I can replicate the problem there.

**Comment by ebeshero** [comment] 2017-03-11 20:48
@lb42 Well I'll be darned! I opened this on my Mac (where oXygen is up-to-date and has the latest bleeding edge TEI dev installed) and all is well with the ODDs. So I think you're right, that my oXygen framework is "out of sorts" on my Ubuntu machine. Hmmm.

**Comment by ebeshero** [comment] 2017-03-11 21:02
And I see everything looks fine with dataRef in my ODDs when change to the current standard framework update, too. I'm sure something's amiss on the Ubuntu oXygen, then, but what a strange error to be seeing!

**Comment by ebeshero** [comment] 2017-03-11 21:21
@lb42 I think I've isolated the problem. If I uninstall the stable TEI framework plugin (6.1.1) in the Ubuntu oXygen, the errors on dataRef disappear. If I install the bleeding-edge dev TEI framework plugin, I don't see errors either. But as soon as I reinstall the stable TEI framework plugin, the errors return. I think the question now is, can anyone else on a Linux machine replicate the problem?

**Comment by ebeshero** [comment] 2017-03-12 19:14
I've asked a friend halfway around the world who works on an Ubuntu installation of oXygen to check this. She confirms, from Madrid, that she sees the same errors I do, and *only* with the current version of oXygen with the current stable oXygen-tei plugin. Without the plugin, all us well with the '<datatype>` element in ODD. Should we report this to the oXygen folks?

**Comment by ebeshero** [comment] 2017-03-12 22:09
Switched to my mac and installed the current stable plugin--and saw the error fire on `<datatype>` as I was writing this:
````
</attDef>
            <attDef ident="ana" mode="replace">
              <datatype><dataRef key="teidata.numeric"/></datatype>
            </attDef>

````
If I sneak an rng: in front of dataRef, as in `<rng:dataRef>` the error disappears. I doubt that's an advisable fix, but it's diagnostic.

**Comment by martindholmes** [comment] 2017-03-12 22:53
The plugin is our responsibility. We do need to release an update to it, but first we have to do an updated release of the Stylesheets, which I believe is imminent, isn't it?

**Comment by lb42** [comment] 2017-03-22 18:25
I believe this may be the same problem as the one James reported with purifying the xInclude exemplar. If you have schematron validation switched on, when processing  a schema in which there is an  `<anyElement>` element which references or requires some namespace, and that namespace is not declared, you will see that bizarre message. In James's case, it's the `<content>` element. In your case I am less sure. I didn't see the error because I didn't have schematron validation switched on.

**Comment by eduarddrenth** [comment] 2017-03-29 05:39
This issue effects me as well. Could this issue effect odd compilation when using chained odd files?

**Comment by hcayless** [comment] 2017-05-25 13:38
We will do a release to fix this.

**Comment by hcayless** [comment] 2017-09-24 13:58
This should have been cleared up in the last release. Closing.

**Closed by hcayless** 2017-09-24 13:58 UTC
Labels: Status: Go, TEI: ODD, Type: Bug
