### ISSUE TITLE
examples in ODD example page do not use ODD pure

### ISSUE THREAD

**Issue by PietroLiuzzo** [TEIC/TEI#1813] opened 2018-09-10 12:31 UTC
This page 
http://www.tei-c.org/guidelines/customization/getting-started-with-p5-odds/

has examples which are not ODD pure (from conversation with  @raffazizzi today in Tokyo.

**Comment by emylonas** [comment] 2018-10-01 15:19
This isn't part of the guidelines. Syd managed to find it on tei-c.org
 at: tei-c.org/opencms_tomcat/lv1/local/tomcat_6.0.14_teicms/webapps/ROOT/export/Guidelines/Customization/odds.xml

We are not sure how it is generated. It was created by Sebastian, and has been edited by Kevin Hawkins, Chris Ruotolo, Julia Flanders and Martin. Last edit was Kevin in 2013.

Assigning to Syd for RNG work (in order to make sure that it all maps and works properly). But open question how to edit and process given its location. Information please.

**Comment by jamescummings** [comment] 2018-10-02 11:37
If you give me the corrections for the page (@sydb) I'm happy to add them to the website version. It has now been sucked into wordpress.

**Comment by lb42** [comment] 2018-10-02 12:02
Sadly, this page has rather more problems than that. The discussion of the xInclude example is incomprehensible, I suspect due to formatting issues.

**Comment by lb42** [comment] 2018-10-02 12:12
Sadly, this page has rather more problems than that. The discussion of the xInclude example is incomprehensible, I suspect due to formatting issues.

**Comment by lb42** [comment] 2018-10-02 12:16
There are two earlier versions of this document in the Github repo: Documents/oddmanual/oddmanual.xml and Documents/oddmanual/index.xml : they are not identical. In an ideal world, there would be a single ODD xml document which could be readily brought up to date. In this sublunary world however I suspect there have been updates and corrections made in some non-TEI format subsequently in a document  accessible only to a few.

**Comment by sydb** [comment] 2018-10-03 00:53
Well, I’m happy to do some updating, but if you’re already on the case, @lb42, you would probably do a better job than I, anyway.
If I am to do this, which document do you think I should start with, or do I have to combine all three?

**Comment by lb42** [comment] 2018-10-04 18:49
I've now had a slightly closer look, and have located what appears to be the most recently revised (2013) XML source of the document. To avoid losing it again, I've checked it into the Documents repo in a new folder called "ODDintro"; to avoid confusion I also renamed the old one "oldODDmanual". I'm happy to work on a revision, bringing it up to date, and removing stuff we no longer believe (or which no longer works), of which there is a mildly distressing quantity. I will aim to get a first version done by Xmas.

**Comment by lb42** [comment] 2018-11-16 19:20
I have now corrected the examples used by this document, but not yet had time to revise the text.

**Comment by jamescummings** [comment] 2019-09-14 10:01
Council decides it should prod @lb42 to see if he still is willing to update the prose. If so, please do.

**Comment by lb42** [comment] 2019-09-14 12:50
I thought I had fixed this. Will have a look when I have better connectivity

**Comment by raffazizzi** [comment] 2020-01-30 20:09
@lb42 Here's a reminder to please have a look at this again.

**Comment by lb42** [comment] 2020-01-30 23:47
Thanks for the reminder Raff and apologies for letting this drop off my desk.  I'll work on it as soon as possible but it's unlikely to be ready for the next release. There are a lot of examples and their formatting is all messed up, quite apart from the content.

**Comment by lb42** [comment] 2020-01-31 17:18
Looking at this again, I think it's not a very useful document as it stands. The Guidelines chapters TD and USE have been extensively revised and expanded since it was written and now contain much more reliable guidance than this in its present state. 

In particular, there are three sections in this document which should (IMHO) be removed -- one describing how GIs can be renamed ; one describing how DTD modules may be combined in DTD syntax; one describing the same thing for RELAXNG modules. Manipulating schema language modules is briefly described in the Guidelines USE chapter with the proviso that it is not recommended; renaming GIs as proposed here doesn't work even if it were a good idea. So I propose to delete these three sections entirely. 

I would then like to revise what's left to give it a more tutorial flavour,  incorporating material currently covered by other "pure ODD" tutorials, and probably something about the new Roma.

Any alternative suggestions?

**Comment by lb42** [comment] 2020-04-22 17:11
The XML source code is now modified as suggested above though the old version has been preserved too. The problem is that the version on the TEI website has not been changed. I don't know how to do that. Probably the link http://www.tei-c.org/guidelines/customization/getting-started-with-p5-odds/ should be suppressed or redirected somehow. So this ticket needs to be reassigned to someone who does.

**Comment by raffazizzi** [comment] 2020-07-28 12:27
@martinascholger since @lb42 has updated the files (located here: https://github.com/TEIC/TEI/tree/dev/Documents/ODDintro) we need to update the page on wordpress (https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/).
I haven't edited the wordpress site before, so is this something that you or @hcayless can do? I'd be happy to shadow so I can also make these changes next time.

**Comment by martinascholger** [comment] 2020-07-29 12:34
I have access to the website. "Getting started ..." is a wordpress page and I am happy to update the page, but I wonder if we should move the files to a new folder (e.g. ODD) in the documentation repo. Here, the text is rendered using CETEIcean (see working papers: http://teic.github.io/TCW/tcw20.html) and we wouldn't have to maintain the XML and the wordpress file. The disadvantage is that header and navigation of the TEI website are missing.

**Comment by martinascholger** [comment] 2020-08-17 11:29
updated wordpress page (https://tei-c.org/guidelines/customization/getting-started-with-p5-odds/) with https://github.com/TEIC/TEI/tree/dev/Documents/ODDintro from @lb42.

**Closed by martinascholger** 2020-08-17 11:29 UTC
Labels: Status: Go
