### ISSUE TITLE
Updating Intro to XML's handling of Validation

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1708] opened 2017-11-17 17:34 UTC
The validation info in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SG.html needs some updating. It needs information on PureODD, a new section on that, or perhaps a mention and to point to the chapter. Council agrees this should definitely cover RELAX NG and discuss the importance of validation.

**Comment by ebeshero** [comment] 2019-12-29 20:08
Working on this ticket at last, I'm noting that we want a new *section* in SG on validation, presumably a top level section. What we currently have is [an internal section called "Validating a Document's Structure"](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SG.html#SG14) followed by several others at the same level all about Relax NG. It would make sense to make "Validating a Document's Structure" be a top-level section in the chapter to contain these other sections, and include the new material we want with links to the ODD documentation chapters there.

**Comment by ebeshero** [comment] 2019-12-30 03:36
With this set of commits, mostly https://github.com/TEIC/TEI/commit/c1131e950220310955f8e557c19952f55a291609, I've made some small but significant updates to our discussion of validation in SG (the Gentle Intro to XML) so that we're now making more of ODD validation. I've also made some minor spot revisions for consistency of phrasing and stye in SG. I think we might be ready to close this ancient ticket and together with #1949 we'll have made some significant improvements to SG. I'd like others to take a look and see if there's anything more you'd like to update or change here. @martinascholger @hcayless @sydb @martindholmes

**Comment by martindholmes** [comment] 2019-12-30 15:46
I've never really understood why this elaborately-worked explanation uses non-TEI elements. It must be completely confusing to people who start by reading this to discover that there's no such element as a `<poem>` in TEI, and that `<line>` is something else entirely from the thing introduced here. Note 16 is almost a cry of despair: "This example is probably not a good practice for most XML projects, since XPath provides ways of distinguishing elements in an XML structure by their position, or the order in which they appear in relation to one another, without the need to give them distinct names." In other words, everything we're explaining here is a) not TEI, and b) not even necessarily good practice. Is it really so hard for people to understand that `<l>` is a line, `<lg>` is a line-group, and `<head>` is a heading?

**Comment by ebeshero** [comment] 2019-12-30 16:38
@martindholmes I’ve wondered about that, too, but it is a Gentle Introduction to XML in general as opposed to TEI in particular. I (and others) teach students this way, to come up with their own elements and attributes to describe a document based on a topic or question that matters to them, so as I was working on this I was getting the spirit of that free form approach—with all of its problems. What we don’t explain or convey here is how the TEI would approach poetry entirely differently—and we could do that, even in that footnote cry of despair that you point out. 

If we are going to teach something about what XML is and does, prior to introducing the TEI, I like how this chapter attempts to show how content modeling and simple validation work. I found myself wondering how many TEI community people come to this page at all, except we were recently reminded by #1949 that they do—and know how to correct it when it’s wrong about things like XPath. It’s a pretty long-established resource for orientation to XML, so I don’t know that we’d want to totally change the examples here. I could, however, see adding some detail about what makes the TEI community approach to a poem much different from this home-cooked example.

**Comment by ebeshero** [comment] 2019-12-30 20:29
There is already a little kind of oblique perspective expressed in the "Gentle Introduction" about the difference between making up one's own encoding for a small project vs. working with a large community. I am wondering if we should really write up a paragraph that directly addresses those differences, and I don't think it would take much. 

It also wouldn't be difficult to change the poetry example just to use TEI elements, especially now that it's a little easier to generate a flowchart of any hierarchy we want to appear there. I think it might be better prioritize the explanation of "any XML" vs "TEI XML" as a way to gently introduce them both.

**Comment by martindholmes** [comment] 2019-12-31 01:46
I think that would be good. Every time I refer someone to this chapter I find myself having to explain that the word "Gentle" in the title doesn't mean what they think it means. Part of this is due to the style, which although entertaining for native speakers, is a little arch and arcane if English isn't your first language. I've seen non-natives struggle with formulations such as `Markup codes such as <para> or \end{list} simply identify a portion of a document and assert of it that ‘the following item is a paragraph’` ("assert of it that" is hard to disentangle). `That is, all one can say about an element called (say) <blort> is that instances of it may (or may not) occur within elements of type <farble>, and that it may (or may not) be decomposed into elements of type <blortette>` is amusing unless, for all you know, "blort", "farble" and "blortette" are English words whose significance you feel you ought to grasp. 
But I often find myself arguing against stylistic elegance and in favour of simplicity in the Guidelines. I know it's an unpopular viewpoint. It comes from all those years teaching ESL.

**Comment by ebeshero** [comment] 2019-12-31 02:29
@martindholmes I was wincing over the `<blort>` and `<blortette>` sentence too for similar reasons, and then I somehow stumbled into an Italian translation of this so-called "Gentle" intro that preserved the element names and wondered how people in another language heard those things. @lujessica and I immediately removed the snotty-sounding "solidus" that apparently means "forward-slash" as one of our first edits, but there is *so* much more to weed out. And I agree with you, it ought to be weeded out--and further I'll say it isn't good *international* style which we ought to be aiming for in our Guidelines.

**Comment by hcayless** [comment] 2019-12-31 03:17
@martindholmes It’s a viewpoint that’s popular with me at least. Agree 100% with @ebeshero that the style isn’t very translatable. I think the rhetoric of it no longer really works either. It’s all “What is this new XML thing?” But the question a modern reader will want answered is “Why are you still using XML? I heard it sucked.”

**Comment by ebeshero** [comment] 2019-12-31 03:36
@hcayless Perhaps there's some reframing we can do without totally rewriting the contents. To me, being compelled by these tickets to finally sit down and read the "Gentle Introduction" closely was a sort of trip back in time, and I have to admit some of the enthusiasm over "hey, look what you can do with making up your own markup" is still kind of appealing. Maybe we can say something about longevity and sustainability of data marked up in well-documented and schematized XML that has given it remarkable resilience as a data format on which the TEI community relies...and I now wonder if we should retitle this ticket.

**Comment by ebeshero** [comment] 2019-12-31 03:38
No, probably open a new ticket. I wanted to address the old ticket that started us down this path in time for the next release. But a complete overhaul may be something we start up after the winter release.

**Comment by lb42** [comment] 2019-12-31 12:28
FWIW, my opinion us that you should stop tinkering around with this ancient monument, hacking off bits here and fitting new pipes there, and instead write a completely new and probably much shorter introduction which provides (a) the basics of how to encode documents in TEI XML (b) the specifics of how the Guidelines as a whole use XML and related technologies. These are two different, but complementary topics. Keep the current "gentle guide" unmodified in the vault as a reminder of days gone by but don't try to make it into something it was never meant to be. 

On the question of style and tone, I am obviously biassed, but I think the criticisms being made rather miss the point that this document was intended to address a different audience from either the novice geek that Hugh imagines or the struggling EFL learner of Martin's dreams. It was intended to ensnare the "humanist scholar" with very little technical background but a desire to understand what the pointy brackets were for. As such, a little  humour, and yes some possibly pretentious vocabulary seemed appropriate to reassure that audience that they were not being addressed by pointy-headed monsters. [And maybe that's just the way I write -- I see I just used the word "ensnare" in the preceding sentence rather than the dull and quotidian "catch" :-)] Anyway, a google search for "gentle introduction sgml" suggests the document was widely praised for its accessibility  back in the day. That's not to say that it does not need major rewriting for today's audience: in fact, I suggested that this would be necessary when the section on XML was bolted on for P4, but there wasn't time.

A new document could start from the introductory slides which we all use when teaching TEI XML, amongst which I am sure there are many commonalities. It should explain the basic ideas:  labelled bracketting as a way of representing a tree structure; why tree structures are useful things to represent; the notions of textual grammar and textual constraints. It should place the ODD language at its centre, and perhaps explain why we don't use any other of the currently available formalisms to express the conceptual model underlying the Guidelines.  

What's wrong with "solidus" btw?

**Comment by sydb** [comment] 2019-12-31 15:00
Have to admit to not reading entire thread in detail, but several thoughts jump to mind:

 * @ebeshero is probably right about re-organizing the RELAX NG stuff as subsections of the validation stuff.
 * Not only is there nothing wrong with “solidus”, which is, after all, the Unicode name for what Americans call “slash” and frequently confuse with backslash, it is probably better _international_ style. (Says this American-English-only speaker. :-)
* The “Gentle Introduction” has been, and perhaps still is, the most successful portion of the _TEI Guidelines_ by a significant margin.
* That said, I think @hcayless and @lb42 are probably right, it is due for a rewrite with a modern audience in mind. (Although my first reaction is to disagree that “it should place the ODD language at its centre”, preferring that this chapter stick to the basics; but I may be wrong about that.)
* The reason, IMHO, for using non-TEI elements in the initial introductory poem is fourfold:
  * To bring to fore that XML is not TEI and TEI is not XML; this chapter is about _XML_.
  * To keep the example short, as having a valid TEI example would require a `<teiHeader>`, `<text>`, and `<body>`.
  * To make it very simple, when explaining validation, to read the schema and visually compare an instance to it.
  * In order to avoid having to explain that we call a “poem” a “line group” abbreviated to “lg” at a point in the prose where, pedagogically, that would be useless information that just makes reading the prose harder.

**Comment by PFSchaffner** [comment] 2019-12-31 16:27
The only problem with 'solidus' is that Unicode has hopelessly confused the traditional typographic distinction between the virgule (the keyboard character, relatively upright, a punctuation mark) and the solidus (more tilted, used to make fractions or separate shillings). The former is U+002F, but Unicode calls it a SOLIDUS (aka 'slash, virgule') rather than a 'virgule'; and the latter is U+2044 FRACTION SLASH (aka 'solidus in typography.') Closing tags require a virgule, or Unicode SOLIDUS, not a solidus, or Unicode FRACTION SLASH. So there's that.

**Comment by PFSchaffner** [comment] 2019-12-31 17:19
Then there's the books that don't use a solidus to separate shillings and pence, but an s-like character (3ʃ6 rather than 3⁄6 or, with a virgule, 3/6).  Close examination is like the Daleks' Reality Bomb: look at anything too closely and it dissolves into disorder.

**Comment by lb42** [comment] 2019-12-31 17:26
Wikipedia (sv slash punctuation) is ever enlightening. If suggests that the usual BRE usage is stroke ... Which I would never have considered. And I note that slash is a 1960s neologism.

**Comment by ebeshero** [comment] 2019-12-31 17:27
@sydb @lb42 @PFSchaffner The first problem we had with "solidus" was that we simply had not encountered it anywhere other than this "Gentle" intorduction. We only understood its meaning from context in the sentence, and there seemed no earthly reason not to call it a forward slash. Anyway, here's English Stack Exchange on the question: 
https://english.stackexchange.com/questions/10993/what-is-the-difference-between-solidus-and-slash

**Comment by ebeshero** [comment] 2019-12-31 17:33
Having been reading the "Gentle Introduction" more closely than usual these past several days, I am not of @lb42 's opinion that it shouldn't be revised and updated. I think most of its substance and examples are fine if only because the syntax we are working with is stable. I think we can rewrite it to update the language and perspective, just as we do any other document in our Guidelines, and I don't think it will involve any revisions that make it run counter to the spirit in which the document was originally written. Revision is, after all, what we do to update anything that's still useful, as this document most certainly is.

**Comment by ebeshero** [comment] 2019-12-31 17:51
Worth considering is that humanities scholars coming to XML probably do so  as I did, in some context *connected* to and influenced by this Gentle Introduction, whether we read it as our first instructional material or not. The witticisms are not really an issue any more than the word "ensnare" which doesn't bother me at all (and "catch"  is more ambiguous anyway). Where the language is abstruse and confounding and verbose (as it is in writing any of us can produce), we should modify it. But the primary issue we're discussing I think is whether the content of the "Gentle Introduction to XML" is not what we want as prefatory material to the TEI Guidelines. I, for one, think we should keep it.

**Comment by PFSchaffner** [comment] 2019-12-31 18:00
> 
> 
> Wikipedia (sv slash punctuation) is ever enlightening. If suggests that the usual BRE usage is stroke ... Which I would never have considered. And I note that slash is a 1960s neologism.

Concerned as I always am to be UK-aware, "stroke" was for me long a puzzle of British English, as in addresses given as '14-stroke-16 Highland Crescent" -- did that mean 14/16 or 14-16? Or something in between, as in the early modern oblique hyphen? It did not occur to me that 'stroke' was a shortening of 'oblique stroke' though I sensed it must be something like that. ... IN teaching I try to avoid the whole 'slash' thing because no one seems to know which are 'forward' and which are 'back'. It's as bad as prone and supine.  Names for punctuation and similar marks are notoriously unstable.

**Comment by martindholmes** [comment] 2019-12-31 18:22
@lb42 The EFL reader is not in my dreams; it's (I hope and believe) now the majority of Guidelines readers. "Solidus" is a lovely word and the technically-correct term, but "slash" is more familiar (and is a loan word in other languages such as Japanese https://jisho.org/search/surasshu) and therefore more accessible; I think if "solidus" is retained, it should be glossed parenthetically with "forward slash". "Ensnare" is also a fine word, but if it doesn't express any more than "catch" would in the same context, then I would be against using it in a document that is intended for a broad audience to many of whom it will be unfamiliar. I like your writing style, and I enjoy your jokes, but if we're serious about communicating well to our entire audience, we need to avoid spurious latinisms, obscure vocabulary, and Nigel Molesworth references, as any fule kno.

**Comment by sydb** [comment] 2019-12-31 19:49
If we’re going to go parenthetical, I would prefer the reverse: use “slash” and gloss it with “(‘/’, U+002F SOLIDUS)”.

**Comment by ebeshero** [comment] 2020-02-10 03:12
@martinascholger Hoping this one is wrapped up and ready to go for the release...Shall we close it?

**Comment by sydb** [comment] 2020-02-11 14:39
While there is still work to be done on the wonderful _Gentle Introduction_, Council feels this ticket can be closed.

**Closed by sydb** 2020-02-11 14:39 UTC
Labels: Status: Go, TEI: Guidelines & Documentation
