### ISSUE TITLE
Bookmark links from non-English examples don't link to bibliography

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#2138] opened 2021-04-29 14:51 UTC
This is harvested from issue #2317, which is actually on a different topic. @lb42 pointed out this problem. The links in the English version of the Guidelines always point to the English bibliography page, but there are examples in the specs pages which are only reffed in the French bibliography. This is an example:

https://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-title.html#index-egXML-d39e47171

The example does not appear in the main spec page in the English Guidelines, so its source doesn't appear in the English bibliography, but it is harvested into the complete examples page in the English Guidelines, and from there the link fails, because it's pointing to the English bibliography. But if you're reading the French spec page and you click on Bibliography, it works:

https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-title.html

**Comment by sydb** [comment] 2021-04-30 13:11
Am I correct that the (or at least a) solution is to change the code that generates the “bibliography” link to recognize that there is no English bibliography entry and thus not create the link?

**Comment by lb42** [comment] 2021-04-30 13:32
Except that there  is a bibliography entry to be linked to. Just not in the English bib!

**Comment by sydb** [comment] 2021-04-30 13:54
Hmmm … so what is the algorithm for ascertaining the link?

~~~
IF there is a <bibl> entry in $language-of-example THEN point to it;
ELSE IF there is a <bibl> entry in $language-of-Guidelines THEN point to it;
ELSE IF there is a <bibl> entry in English THEN point to it;
ELSE do not provide a _bibl_ link
~~~
?

**Comment by martindholmes** [comment] 2021-04-30 14:44
Or possibly harvest all bibl entries that are pointed to from egXMLs anywhere, and pull them into each language's bibliography file. Or we simply have a single, centralized bibliography file that all the languages use.

I think I favour the latter, for simplicity. People do love massive bibliographies (or at least, they love making them and including them in every article they write). Since all egXMLs are by definition included in all language versions of the Guidelines (in the "all examples" pages), all bibliography entries might as well be there too.

**Comment by sydb** [comment] 2021-04-30 15:01
Oh. I do like that one-BIBL-to-rule-them-all idea. But it does not change the _algorithm_ for what to point to, just the execution, right? (I.e., instead of looking in the `Guidelines/$LANG/BIB-Bibliography.xml` file, we would be looking for the `bibl[lang($LANG)]` entry.)

**Comment by martindholmes** [comment] 2021-04-30 15:17
I think the algorithm is just straightforward if they're all in the same file: we don't have to care about the language, because it's irrelevant. All versions of the GLines would have the same complete bibliography.

**Comment by martindholmes** [comment] 2021-04-30 15:29
@sydb and I looked into this, and it seems that there is only one centralized bibliography, but when a specific language version of the Guidelines is being built, all entries from other languages are filtered out. This is a mistake, because all egXMLs are included from all languages on the all-examples pages, so we shouldn't be filtering out that stuff from the Guidelines. The first thing to do is to turn that filtering off, so the broken links are fixed; following that, we should look at whether any filtering should take place -- for example, we could filter any item that isn't pointed at from any source file, unless it's in the reading-list section.

**Comment by peterstadler** [comment] 2022-04-02 10:36
duplicate of #2106, closing here

**Closed as completed by peterstadler** 2022-04-02 10:36 UTC
Labels: Type: Bug, TEI: Guidelines & Documentation, TEI: Build Process, CouncilResponsibility
