### ISSUE TITLE
rs should contain q and quote

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1531] opened 2016-10-30 17:27 UTC
As raised [on the TEI list on Oct. 30, 2016](https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;2bb22eab.1610), we can't nest a `<q>` (or a `<quote>` element inside a `<rs>` element . The examples from Scott Vanderbilt's archaeology project posted on the list look like unusual but plausible use-cases fpr `<rs>` to contain quoted material, and might be useful in the Guidelines to broaden diversity of examples in the Guidelines, should we decide this ticket is "Go." This example looks especially useful:

```
   <rs type="findspot">in excavation, re-used in a fourth-century
   <q>chalet</q></rs>
```

and perhaps this:

```
<rs>The town <quote>formerly known as Princeton</quote></rs>
```

**Comment by peterstadler** [comment] 2016-10-30 21:15
As I just wrote on TEI-L, I'd support this FR but was down voted once, see http://tei-l.970651.n3.nabble.com/quotes-in-names-tp4026585.html for some historic discussion.

**Comment by lb42** [comment] 2016-10-30 21:32
Firstly, as I said on the thread on TEI-L, it seems wrong to me to use &lt;rs> for a descriptive phrase like this. It's meant to behave like a name : an alternative to  &lt;placeName> or &lt;persName>. You would never say "I found this axe at 'in excavation reused in a 4th century chalet', nor expect that description to turn up in a list of places. Hence my suggestion of using a more neutral block level (and typable) element such as  &lt;ab> to record these find-place descriptions. 
Secondly, if you insist on using a phrase level element such as  &lt;rs>, you only have phrase level content at your disposal. So you could use  &lt;mentioned> or  &lt;soCalled> (either of which seems to suit the "chalet" example, or (if you just want to record the presence of the quote marks)  &lt;hi>.
Thirdly, the phrase "formerly known as Princeton" is not a quote, so far as I can tell, except from me! 
Introducing  &lt;q> into the content of a phrase level element would disrupt the current model quite severely. One prototypical use for  &lt;q> is "stuff in quotes" (it's almost a synonym for  &lt;hi rend="quoted">). The other is to encode direct speech without the bother of having to wrap each part in  &lt;p> elements. That's why it's in model.inter rather than model.phrase.

**Comment by ebeshero** [comment] 2016-10-30 22:16
That is just the problem that people tend to have with `<rs>`, though, isn't it? It's a phrase that's kind of like a name, but isn't.  It's a "string" that "refers": that makes it some snippet of text, and we shouldn't have to make workarounds when a string that refers happens to have quotation marks in it for whatever reason it happens to have quotation marks. A "referring string" might well containo spoken words, or words that are quoted from another source. If we can use `<soCalled>` why can't we also use `<q>` as well as `<hi rend="quote">`? Shouldn't all these options be available to the encoder? What is so disruptive about permitting `<q>` and `<quote>` if we're permitted `<mentioned>` and `<soCalled>`? 

I think it's a little premature to close this discussion.

**Comment by lb42** [comment] 2016-10-30 22:21
Sorry, didn't mean to close the ticket. But I do think the proposal is disruptive of the current hierarchy of content models. mentioned and soCalled and hi are phrase level elements; q is not. If it were you wouldn't be able to markup passages of direct speech without enclosing each one within a &lt;p> for example.

**Comment by ebeshero** [comment] 2016-10-30 22:51
Okay, so the issue, if I understand this right, is that `<q>` isn't a "phrase-level" element, but that  `<rs>` *is* phrase-level. Even so, we use `<q>` above and below the paragraph level, and that makes it difficult to explain what we mean by a "phrase level" element. Well, of course `<rs>` is a member of model.nameLike, and that is a member of model.phrase. I understand the content-model problem, but I'm still trying to wrap my head around why we disallow `<q>` and `<quote>` from that which is model.phrase. 

The issue of direct speech seems to be one of scope, but `<q>` is used all the time inside what most of us think of conventionally as "just a phrase." I'm studying [model.phrase](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.phrase.html) and wondering if the idea was to exclude quoteLike and qLike` because these are always (by the Guidelines) considered to be above phrase-level by definition. 

Frankly, I'm confused by the dynamic applicability of [model.inter](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.inter.html) which permits the use of qLike and quoteLike above the paragraph level AND below it. The application below the paragraph level seems to be the question here. Okay, obviously we don't want `<rs>` to be so big and expansive that it can contain whole paragraphs the way `<q>` does--I get that that would be the disruptive thing. rs is a member of model.phrase for good reason. 

But what about permitting `<q>` and `<quote>` within `<rs>` and other phrase level elements because they are every bit as applicable as other things we treat as phrases in Real Life? You're going to tell me this is something people can do for themselves at ODD level, and I won't disagree, except they'd be doing something that explicitly (now) cuts against our hierarchy of content models. Sigh.

**Comment by ebeshero** [comment] 2016-10-30 22:54
After all that, here's my question: Would it be an awful thing to permit a member of model.inter inside a member of model.phrase?

**Comment by ebeshero** [comment] 2017-02-06 11:04
F2F subgroup recommends giving rs membership in model.qLike .

**Comment by sydb** [comment] 2017-02-06 14:48
@sydb will compare lists of elements that have model.phraseSeq as content and those that have model.paraContent. Also to take a look at how big a deal it might be to move `<q>` out of model.qLike.

**Comment by sydb** [comment] 2018-01-11 14:13
Have %macro.phraseSeq; in their content model:
`<abbr>`, `<actor>`, `<addName>`, `<addrLine>`, `<affiliation>`,
`<author>`, `<biblScope>`, `<birth>`, `<bloc>`, `<catchwords>`,
`<citedRange>`, `<cl>`, `<colophon>`, `<country>`, `<death>`,
`<distinct>`, `<distributor>`, `<district>`, `<docAuthor>`,
`<docDate>`, `<edition>`, `<editor>`, `<education>`, `<eg>`,
`<email>`, `<expan>`, `<explicit>`, `<extent>`, `<faith>`,
`<finalRubric>`, `<floruit>`, `<foreign>`, `<forename>`, `<fw>`,
`<genName>`, `<geoDecl>`, `<geogFeat>`, `<geogName>`, `<gloss>`,
`<headItem>`, `<headLabel>`, `<heraldry>`, `<incipit>`, `<label>`,
`<material>`, `<measure>`, `<mentioned>`, `<name>`, `<nameLink>`,
`<nationality>`, `<num>`, `<objectType>`, `<offset>`, `<orgName>`,
`<origPlace>`, `<persName>`, `<phr>`, `<placeName>`, `<pubPlace>`,
`<publisher>`, `<region>`, `<residence>`, `<role>`, `<roleDesc>`,
`<roleName>`, `<rs>`, `<rubric>`, `<s>`, `<secFol>`, `<settlement>`,
`<sex>`, `<soCalled>`, `<socecStatus>`, `<speaker>`, `<stamp>`,
`<street>`, `<surname>`, `<term>`, `<textLang>`, `<watermark>`,
`<wit>`, and `<witDetail>`.

Have %macro.paraContent; in their content model:
`<ab>`, `<add>`, `<camera>`, `<caption>`, `<case>`, `<colloc>`, `<corr>`, `<damage>`, `<def>`, `<del>`, `<docEdition>`, `<emph>`, `<gen>`, `<gram>`, `<hi>`, `<hyph>`, `<iType>`, `<imprimatur>`, `<lang>`, `<lbl>`, `<mod>`, `<mood>`, `<number>`, `<orig>`, `<orth>`, `<p>`, `<per>`, `<pos>`, `<pron>`, `<ref>`, `<reg>`, `<restore>`, `<retrace>`, `<rhyme>`, `<salute>`, `<secl>`, `<seg>`, `<sic>`, `<signed>`, `<sound>`, `<stress>`, `<subc>`, `<supplied>`, `<surplus>`, `<syll>`, `<tech>`, `<title>`, `<titlePart>`, `<tns>`, `<u>`, `<unclear>`, `<usg>`, and `<writing>`.

GI | phraseSeq | paraContent
---|-----------|------------
TEI |   | 
ab |   | macro.paraContent
abbr |  macro.phraseSeq | 
abstract |   | 
accMat |   | 
acquisition |   | 
activity |   | 
actor |  macro.phraseSeq | 
add |   | macro.paraContent
addName |  macro.phraseSeq | 
addSpan |   | 
additional |   | 
additions |   | 
addrLine |  macro.phraseSeq | 
address |   | 
adminInfo |   | 
affiliation |  macro.phraseSeq | 
age |   | 
alt |   | 
altGrp |   | 
altIdent |   | 
altIdentifier |   | 
alternate |   | 
am |   | 
analytic |   | 
anchor |   | 
annotationBlock |   | 
anyElement |   | 
app |   | 
appInfo |   | 
application |   | 
arc |   | 
argument |   | 
att |   | 
attDef |   | 
attList |   | 
attRef |   | 
author |  macro.phraseSeq | 
authority |   | 
availability |   | 
back |   | 
bibl |   | 
biblFull |   | 
biblScope |  macro.phraseSeq | 
biblStruct |   | 
bicond |   | 
binary |   | 
binaryObject |   | 
binding |   | 
bindingDesc |   | 
birth |  macro.phraseSeq | 
bloc |  macro.phraseSeq | 
body |   | 
broadcast |   | 
byline |   | 
c |   | 
cRefPattern |   | 
caesura |   | 
calendar |   | 
calendarDesc |   | 
camera |   | macro.paraContent
caption |   | macro.paraContent
case |   | macro.paraContent
castGroup |   | 
castItem |   | 
castList |   | 
catDesc |   | 
catRef |   | 
catchwords |  macro.phraseSeq | 
category |   | 
cb |   | 
cell |   | 
certainty |   | 
change |   | 
channel |   | 
char |   | 
charDecl |   | 
charName |   | 
charProp |   | 
choice |   | 
cit |   | 
citedRange |  macro.phraseSeq | 
cl |  macro.phraseSeq | 
classCode |   | 
classDecl |   | 
classRef |   | 
classSpec |   | 
classes |   | 
climate |   | 
closer |   | 
code |   | 
collation |   | 
collection |   | 
colloc |   | macro.paraContent
colophon |  macro.phraseSeq | 
cond |   | 
condition |   | 
constitution |   | 
constraint |   | 
constraintSpec |   | 
content |   | 
corr |   | macro.paraContent
correction |   | 
correspAction |   | 
correspContext |   | 
correspDesc |   | 
country |  macro.phraseSeq | 
creation |   | 
custEvent |   | 
custodialHist |   | 
damage |   | macro.paraContent
damageSpan |   | 
dataFacet |   | 
dataRef |   | 
dataSpec |   | 
datatype |   | 
date |   | 
dateline |   | 
death |  macro.phraseSeq | 
decoDesc |   | 
decoNote |   | 
def |   | macro.paraContent
default |   | 
defaultVal |   | 
del |   | macro.paraContent
delSpan |   | 
depth |   | 
derivation |   | 
desc |   | 
dictScrap |   | 
dim |   | 
dimensions |   | 
distinct |  macro.phraseSeq | 
distributor |  macro.phraseSeq | 
district |  macro.phraseSeq | 
div |   | 
div1 |   | 
div2 |   | 
div3 |   | 
div4 |   | 
div5 |   | 
div6 |   | 
div7 |   | 
divGen |   | 
docAuthor |  macro.phraseSeq | 
docDate |  macro.phraseSeq | 
docEdition |   | macro.paraContent
docImprint |   | 
docTitle |   | 
domain |   | 
eLeaf |   | 
eTree |   | 
edition |  macro.phraseSeq | 
editionStmt |   | 
editor |  macro.phraseSeq | 
editorialDecl |   | 
education |  macro.phraseSeq | 
eg |  macro.phraseSeq | 
egXML |   | 
elementRef |   | 
elementSpec |   | 
email |  macro.phraseSeq | 
emph |   | macro.paraContent
empty |   | 
encodingDesc |   | 
entry |   | 
entryFree |   | 
epigraph |   | 
epilogue |   | 
equipment |   | 
equiv |   | 
etym |   | 
event |   | 
ex |   | 
exemplum |   | 
expan |  macro.phraseSeq | 
explicit |  macro.phraseSeq | 
extent |  macro.phraseSeq | 
f |   | 
fDecl |   | 
fDescr |   | 
fLib |   | 
facsimile |   | 
factuality |   | 
faith |  macro.phraseSeq | 
figDesc |   | 
figure |   | 
fileDesc |   | 
filiation |   | 
finalRubric |  macro.phraseSeq | 
floatingText |   | 
floruit |  macro.phraseSeq | 
foliation |   | 
foreign |  macro.phraseSeq | 
forename |  macro.phraseSeq | 
forest |   | 
form |   | 
formula |   | 
front |   | 
fs |   | 
fsConstraints |   | 
fsDecl |   | 
fsDescr |   | 
fsdDecl |   | 
fsdLink |   | 
funder |   | 
fvLib |   | 
fw |  macro.phraseSeq | 
g |   | 
gap |   | 
gb |   | 
gen |   | macro.paraContent
genName |  macro.phraseSeq | 
geo |   | 
geoDecl |  macro.phraseSeq | 
geogFeat |  macro.phraseSeq | 
geogName |  macro.phraseSeq | 
gi |   | 
gloss |  macro.phraseSeq | 
glyph |   | 
glyphName |   | 
gram |   | macro.paraContent
gramGrp |   | 
graph |   | 
graphic |   | 
group |   | 
handDesc |   | 
handNote |   | 
handNotes |   | 
handShift |   | 
head |   | 
headItem |  macro.phraseSeq | 
headLabel |  macro.phraseSeq | 
height |   | 
heraldry |  macro.phraseSeq | 
hi |   | macro.paraContent
history |   | 
hom |   | 
hyph |   | macro.paraContent
hyphenation |   | 
iNode |   | 
iType |   | macro.paraContent
ident |   | 
idno |   | 
if |   | 
iff |   | 
imprimatur |   | macro.paraContent
imprint |   | 
incident |   | 
incipit |  macro.phraseSeq | 
index |   | 
institution |   | 
interaction |   | 
interp |   | 
interpGrp |   | 
interpretation |   | 
item |   | 
join |   | 
joinGrp |   | 
keywords |   | 
kinesic |   | 
l |   | 
label |  macro.phraseSeq | 
lacunaEnd |   | 
lacunaStart |   | 
lang |   | macro.paraContent
langKnowledge |   | 
langKnown |   | 
langUsage |   | 
language |   | 
layout |   | 
layoutDesc |   | 
lb |   | 
lbl |   | macro.paraContent
leaf |   | 
lem |   | 
lg |   | 
licence |   | 
line |   | 
link |   | 
linkGrp |   | 
list |   | 
listApp |   | 
listBibl |   | 
listChange |   | 
listEvent |   | 
listForest |   | 
listNym |   | 
listOrg |   | 
listPerson |   | 
listPlace |   | 
listPrefixDef |   | 
listRef |   | 
listRelation |   | 
listTranspose |   | 
listWit |   | 
localName |   | 
locale |   | 
location |   | 
locus |   | 
locusGrp |   | 
m |   | 
macroRef |   | 
macroSpec |   | 
mapping |   | 
material |  macro.phraseSeq | 
measure |  macro.phraseSeq | 
measureGrp |   | 
media |   | 
meeting |   | 
memberOf |   | 
mentioned |  macro.phraseSeq | 
metDecl |   | 
metSym |   | 
metamark |   | 
milestone |   | 
mod |   | macro.paraContent
model |   | 
modelGrp |   | 
modelSequence |   | 
moduleRef |   | 
moduleSpec |   | 
monogr |   | 
mood |   | macro.paraContent
move |   | 
msContents |   | 
msDesc |   | 
msFrag |   | 
msIdentifier |   | 
msItem |   | 
msItemStruct |   | 
msName |   | 
msPart |   | 
musicNotation |   | 
name |  macro.phraseSeq | 
nameLink |  macro.phraseSeq | 
namespace |   | 
nationality |  macro.phraseSeq | 
node |   | 
normalization |   | 
notatedMusic |   | 
note |   | 
notesStmt |   | 
num |  macro.phraseSeq | 
number |   | macro.paraContent
numeric |   | 
nym |   | 
oRef |   | 
objectDesc |   | 
objectType |  macro.phraseSeq | 
occupation |   | 
offset |  macro.phraseSeq | 
opener |   | 
org |   | 
orgName |  macro.phraseSeq | 
orig |   | macro.paraContent
origDate |   | 
origPlace |  macro.phraseSeq | 
origin |   | 
orth |   | macro.paraContent
outputRendition |   | 
p |   | macro.paraContent
pRef |   | 
param |   | 
paramList |   | 
paramSpec |   | 
particDesc |   | 
pause |   | 
pb |   | 
pc |   | 
per |   | macro.paraContent
performance |   | 
persName |  macro.phraseSeq | 
person |   | 
personGrp |   | 
persona |   | 
phr |  macro.phraseSeq | 
physDesc |   | 
place |   | 
placeName |  macro.phraseSeq | 
population |   | 
pos |   | macro.paraContent
postBox |   | 
postCode |   | 
postscript |   | 
precision |   | 
prefixDef |   | 
preparedness |   | 
principal |   | 
profileDesc |   | 
projectDesc |   | 
prologue |   | 
pron |   | macro.paraContent
provenance |   | 
ptr |   | 
pubPlace |  macro.phraseSeq | 
publicationStmt |   | 
publisher |  macro.phraseSeq | 
punctuation |   | 
purpose |   | 
q |   | 
quotation |   | 
quote |   | 
rdg |   | 
rdgGrp |   | 
re |   | 
recordHist |   | 
recording |   | 
recordingStmt |   | 
redo |   | 
ref |   | macro.paraContent
refState |   | 
refsDecl |   | 
reg |   | macro.paraContent
region |  macro.phraseSeq | 
relatedItem |   | 
relation |   | 
remarks |   | 
rendition |   | 
repository |   | 
residence |  macro.phraseSeq | 
resp |   | 
respStmt |   | 
respons |   | 
restore |   | macro.paraContent
retrace |   | macro.paraContent
revisionDesc |   | 
rhyme |   | macro.paraContent
role |  macro.phraseSeq | 
roleDesc |  macro.phraseSeq | 
roleName |  macro.phraseSeq | 
root |   | 
row |   | 
rs |  macro.phraseSeq | 
rubric |  macro.phraseSeq | 
s |  macro.phraseSeq | 
said |   | 
salute |   | macro.paraContent
samplingDecl |   | 
schemaRef |   | 
schemaSpec |   | 
scriptDesc |   | 
scriptNote |   | 
scriptStmt |   | 
seal |   | 
sealDesc |   | 
secFol |  macro.phraseSeq | 
secl |   | macro.paraContent
seg |   | macro.paraContent
segmentation |   | 
sense |   | 
sequence |   | 
series |   | 
seriesStmt |   | 
set |   | 
setting |   | 
settingDesc |   | 
settlement |  macro.phraseSeq | 
sex |  macro.phraseSeq | 
shift |   | 
sic |   | macro.paraContent
signatures |   | 
signed |   | macro.paraContent
soCalled |  macro.phraseSeq | 
socecStatus |  macro.phraseSeq | 
sound |   | macro.paraContent
source |   | 
sourceDesc |   | 
sourceDoc |   | 
sp |   | 
spGrp |   | 
space |   | 
span |   | 
spanGrp |   | 
speaker |  macro.phraseSeq | 
specDesc |   | 
specGrp |   | 
specGrpRef |   | 
specList |   | 
sponsor |   | 
stage |   | 
stamp |  macro.phraseSeq | 
state |   | 
stdVals |   | 
street |  macro.phraseSeq | 
stress |   | macro.paraContent
string |   | 
styleDefDecl |   | 
subc |   | macro.paraContent
subst |   | 
substJoin |   | 
summary |   | 
superEntry |   | 
supplied |   | macro.paraContent
support |   | 
supportDesc |   | 
surface |   | 
surfaceGrp |   | 
surname |  macro.phraseSeq | 
surplus |   | macro.paraContent
surrogates |   | 
syll |   | macro.paraContent
symbol |   | 
table |   | 
tag |   | 
tagUsage |   | 
tagsDecl |   | 
taxonomy |   | 
tech |   | macro.paraContent
teiCorpus |   | 
teiHeader |   | 
term |  macro.phraseSeq | 
terrain |   | 
text |   | 
textClass |   | 
textDesc |   | 
textLang |  macro.phraseSeq | 
textNode |   | 
then |   | 
time |   | 
timeline |   | 
title |   | macro.paraContent
titlePage |   | 
titlePart |   | macro.paraContent
titleStmt |   | 
tns |   | macro.paraContent
trailer |   | 
trait |   | 
transcriptionDesc |   | 
transpose |   | 
tree |   | 
triangle |   | 
typeDesc |   | 
typeNote |   | 
u |   | macro.paraContent
unclear |   | macro.paraContent
undo |   | 
unicodeName |   | 
usg |   | macro.paraContent
vAlt |   | 
vColl |   | 
vDefault |   | 
vLabel |   | 
vMerge |   | 
vNot |   | 
vRange |   | 
val |   | 
valDesc |   | 
valItem |   | 
valList |   | 
value |   | 
variantEncoding |   | 
view |   | 
vocal |   | 
w |   | 
watermark |  macro.phraseSeq | 
when |   | 
width |   | 
wit |  macro.phraseSeq | 
witDetail |  macro.phraseSeq | 
witEnd |   | 
witStart |   | 
witness |   | 
writing |   | macro.paraContent
xenoData |   | 
xr |   | 
zone |   |

**Comment by sydb** [comment] 2018-01-17 22:21
OK, sorry, but almost a year later someone is going to have to remind me of what we meant by “Also to take a look at how big a deal it might be to move `<q>` out of model.qLike”.

**Comment by sarcanon** [comment] 2018-07-23 18:48
I feel like something drastic needs to happen to get this ticket moved along. *Googles _self-immolation_...*

**Comment by lb42** [comment] 2018-07-23 18:53
I don't see that any of the doubts raised at the start of this thread have been addressed in subsequent discussion. So probably self immolation is your best course.:grinning:

**Comment by ebeshero** [comment] 2018-07-23 19:24
Well, short of such violent metaphorical drastic measures, we could put a Guidelines 3.5.0 milestone marker on this. Apparently we *were* intending to implement this after all...

**Comment by jamescummings** [comment] 2018-07-23 20:11
I'm still of the opinion that this is a mis-use of `<rs>`. I still think @lb42 has it right in October 2016 https://github.com/TEIC/TEI/issues/1531#issuecomment-257180878 

Can someone provide me an example of something which is truly a general purpose name or string referencing a name (like 'he', 'she', etc.) that needs quotes inside it? (i.e. that shouldn't be just marked with `<name>`?)

**Comment by hcayless** [comment] 2018-07-23 20:35
I guess the larger issue is that `<q>` is meant to mark "quoted" text, and that can happen at any level. Not thinking so much about `<rs>` here, but any name: what about Constantino "Big" Paul Castellano, e.g.? I know there are other ways to do it, but it seems weird that I can't use the particular element designed to mark quoted text.

**Comment by ebeshero** [comment] 2018-07-23 20:36
How about this for an example, making a point of nesting the `<q>`: 
```
<rs>the one who goes by <q>he who must not be named</q></rs>
```

**Comment by ebeshero** [comment] 2018-07-23 20:53
Of course you could use `<soCalled>` in the previous one, so here's another:
```
<rs>the one who coined the phrase <quote>the buck stops here</quote></rs>
```

**Comment by jamescummings** [comment] 2018-07-23 21:18
@hcayless Again, that isn't an rs, that is a proper name. So use name or persName.

@ebeshero Again, that isn't an rs that is a sentence that contains an rs. I'd say `<rs rend="quoted">he who must not be named</rs>'  In the second example it is `<rs>the one</rs>`.

I just feel all of these are abuse of rs, I might be in the minority but just trying to be honest.   

I should state that I'm not adverse to rs having q in its content model... just still haven't seen an example that really looks like an rs with a quote mark inside.  I just want a really good example that no one can argue with. ;-)  Or since a F2F subgroup already decided to allow it.... go ahead but we should be clear what we want to use it for and not encourage the kind of tag abuse (IMHO) that started this ticket.

**Comment by ebeshero** [comment] 2018-07-23 21:30
@jamescummings Perhaps you don't yet know to whom "the one" refers and aren't in a position to give it a `@ref` attribute on first encoding. We don't always start projects with full-blown personographies.

**Comment by jamescummings** [comment] 2018-07-23 21:31
@ebeshero Sure... then you don't give it a ref... But that doesn't mean you should be wrapping whole phrases and sentences in rs. IMHO.

**Comment by ebeshero** [comment] 2018-07-23 21:31
@jamescummings My point is that it *does* sometimes make a difference to capture a full "referencing string" and abbreviating it to "the one" strikes me as manifestly improper because it's semantically incomplete.

**Comment by jamescummings** [comment] 2018-07-23 21:33
How is 'the one' semantically incomplete but 'the fighter' not?

**Comment by ebeshero** [comment] 2018-07-23 21:33
@jamescummings Imagine capturing every referencing string used for a particular person, even when you *do* have them filed in a personography and can use `@ref`. Perhaps the project is to capture and extract a list of all phrases used to refer to a particular person (and not to other persons). I'd want to pan outward a little bit and having `<rs>` capture a phrase with a quote inside it doesn't seem far-fetched to me.

**Comment by ebeshero** [comment] 2018-07-23 21:34
@jamescummings "the fighter" in a project full of warriors might well be semantically incomplete without the fuller context supplied by the thing he'd say.

**Comment by ebeshero** [comment] 2018-07-23 21:35
@jamescummings It's simply a matter of precision.

**Comment by jamescummings** [comment] 2018-07-23 21:35
The example is:

```xml
<s n="2">
 <rs xml:id="R4">The fighter</rs> is serving 30-40 years
 for a 1975 armed robbery conviction in <rs xml:id="R5">the penitentiary</rs>.
</s>
````
Do you think the findspot example that started this a valid use?

**Comment by ebeshero** [comment] 2018-07-23 21:36
@jamescummings Sure, there's nothing invalid about this use. And this example is not relevant to the discussion of whether `<q>` or `<quote>` should be used inside `<rs>`.

**Comment by jamescummings** [comment] 2018-07-23 21:37
But it is the example which the original poster cited as the reason for this ticket?!!

```xml
   <rs type="findspot">in excavation, re-used in a fourth-century
   <q>chalet</q></rs>
````
Is just pure abuse to me.

**Comment by hcayless** [comment] 2018-07-23 21:39
> Again, that isn't an rs, that is a proper name. So use name or persName.
@jamescummings Can't. Their content models don't permit it. `<q>`'s note even says that it may be thought of as syntactic sugar for `<hi rend="quote">` in some circumstances, but it can't be used in the same places as `<hi>`.

**Comment by jamescummings** [comment] 2018-07-23 21:40
No, the example I posted (the fighter) is one from the Guidelines.. what we currently recommend.

**Comment by ebeshero** [comment] 2018-07-23 21:41
@jamescummings Yep, and I see how you're using it to suggest a sort of minimum valid length for an `<rs>`, but I don't think it holds water...I *do* think we can do a better job to articulate a limit of applicability for `<rs>`, but I wouldn't be in favor of limiting it to no more than two words in the string.

**Comment by jamescummings** [comment] 2018-07-23 21:42
@hcayless And that is indeed a good argument for it.  As I said, I'm not adverse to the idea... just haven't had an example given that does it for me personally.  If allowing in rs (which is meant to stand in for a name or string referring to a name) then it also needs to be allowed in name, persName, placeName, etc.

**Comment by ebeshero** [comment] 2018-07-23 21:42
Very much agreed on that point. But I rather like my examples, and I think @jamescummings might well reconsider them... ;-)

**Comment by jamescummings** [comment] 2018-07-23 21:43
@ebeshero It is nothing to do with its length, but its semantics. An rs IMHO is a word or phrase standing in for a name. People keep posting examples which don't do that.

**Comment by ebeshero** [comment] 2018-07-23 21:44
How is this example not standing in for a name? 
```
<rs>the one who coined the phrase <quote>the buck stops here</quote></rs>
```

**Comment by ebeshero** [comment] 2018-07-23 21:45
Again, I'm going to say, in the example above, "the one" isn't enough to distinguish the individual precisely. We need the rest to make it clear who is being referred to.

**Comment by jamescummings** [comment] 2018-07-23 21:45
@ebeshero If I reconsider, in your 'the one who goes by "he who must not be named"' example, to me, still, the bit that is standing in for the name is 'he who must not be named' I guess. So I'd still mark that be up as an rs, but not the whole phrase.  Otherwise you'd have to mark up "The one who goes by James Cummings" as a persName rather than just James Cummings.  (If you see what I mean?)

**Comment by ebeshero** [comment] 2018-07-23 21:47
Sorry--dang tick marks! ;-)

**Comment by ebeshero** [comment] 2018-07-23 21:48
My problem with that example is that it's probably better to use <soCalled>...</soCalled> there, which *is* permitted. So I turned my attention to quotable aphorisms, on the formula of, "the one who quipped 'X cool statement'.

**Comment by jamescummings** [comment] 2018-07-23 21:51
That is closer, but again, in that instance the whole restrictive relative clause shouldn't be marked up as rs. The whole thing is not standing in place for a name, IMHO.

**Comment by ebeshero** [comment] 2018-07-23 21:51
A reminder of the content model of `<rs>`: 
```
<content>
 <macroRef key="macro.phraseSeq"/>
</content>
```

It's not an issue for an `<rs>` to be a phrase-level element.

**Comment by ebeshero** [comment] 2018-07-23 21:53
@jamescummings I'm pretty serious about this: if it were my project (and sometimes it is), I'd want full-blown distinguishing phrases and dependent clauses when they are dedicated to identifying a particular named entity. I'd not be content with delimiting `<rs>` to the shortest possible definable markup. There are good reasons for wanting this, including the attribution of spoken expressions to an individual.

**Comment by jamescummings** [comment] 2018-07-23 21:59
For spoken expressions, don't we already have 'said'?  We clearly have differing understandings of what 'rs' is for... And I'm certainly not against it (and *Name) having 'q' in its content model. I just keep seeing things as examples that I really think 'rs' was intended for. Why would you be using rs instead of any of the other possibilities?

**Comment by hcayless** [comment] 2018-07-23 21:59
> And that is indeed a good argument for it. As I said, I'm not adverse to the idea... just haven't had an example given that does it for me personally. If allowing in rs (which is meant to stand in for a name or string referring to a name) then it also needs to be allowed in name, persName, placeName, etc.
@jamescummings That was my point. If it should be allowed in `<name>` then it should presumably be allowed in the other name-like elements. I suspect the problem is that `<q>` is trying to do too much.

**Comment by ebeshero** [comment] 2018-07-23 22:03
Think about this in terms of supporting serious research questions, which is the spirit of the original post in this ticket. The phrase-level aspect of `<rs>` has made it flexible for people to apply to long or short passages. To be sure, it can be all to easily applied wrongly where people ought to be using things like `<seg>`, but as long as a string of words can be said to refer to named somethings-or-others, I don't think we should be keeping `<q>` out of it. There's nothing wrong with using `<q>` for spoken expressions, but if we really want to prevent people from saying, "use a different element", then let's consider a distinguishing expression that was written rather than spoken.

**Comment by sydb** [comment] 2018-07-24 00:31
While I have not read every snippet of today’s detailed conversation, I can say reasonably confidently that (IMHO):
1. @jamescummings is correct, the original post is an abuse of `<rs>`
1. @ebeshero is correct, there are cases where `<q>` inside `<rs>` (or `<name>`, I suppose) is quite reasonable. I think the buck stops here example is a good one.

But @lb42 has really hit the nail on the head — due to the way TEI classes are set up, this may (or may not) turn out to be quite hard to do. E.g., adding model.qLike to macro.phraseSeq is likely to result in ambiguous content models, no? I’m going to play a little and get back to you with a preliminary on that.

**Comment by sydb** [comment] 2018-07-24 00:50
Hmnmm… I just tried it. I created a copy of the current 'dev' branch that had no changes except that I added model.qLike to macro.phraseSeq. I did not notice any new icky errors go buy during the build. I then built a tiny little XML file that had a `<q>` inside an `<rs>` and used the tei_all.dtd. I expected to get ambiguous content model errors, but neither oXygen nor xmllint complained at all.

So I have just checked it in at 206c146, and we’ll see if Mr. Jenkins or anyone else finds something to complain about. (In which case it is quite easy to back out even w/o the use of git version control: just delete “<classRef key="model.qLike"/>” (currently line 28) from Source/Specs/macro.phraseSeq.xml.)

**Comment by lb42** [comment] 2018-07-24 09:53
You won't be surprised to hear that I share James's reservations about this change.The OP's use case is invalid, and the only arguments advanced in favour of making the change seem purely suppositious and theoretical.  A subgroup of council can change its mind, surely?

**Comment by sydb** [comment] 2018-09-07 04:08
Per Council meeting, ticket closed. Those interested may open a new ticket for providing better examples in GLs.

**Closed by sydb** 2018-09-07 04:08 UTC
Labels: Status: Needs Discussion, Type: FeatureRequest
