### ISSUE TITLE
metamark: examples missing

### ISSUE THREAD

**Issue by Martin-de-la-Iglesia** [TEIC/TEI#1651] opened 2017-06-06 09:24 UTC
Somehow I don't see any examples section at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-metamark.html

**Comment by jamescummings** [comment] 2017-06-06 09:58
Confirmed.  This is because the only example provided at https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/metamark.xml#L33-L40 
is in Norwegian and marked as so.

This strikes me as a corrigible error.  IMHO I think we should do two things:

1) Add an English example to the spec file

2) Modify the XSLT producing the Guidelines reference pages. Presumably it currently is only putting out exemplum marked as 'en' in the English Guidelines?  The default action should be that it puts out all examples _except_ those specifically marked as a language we produce the guidelines reference pages in?  i.e. [English] [Deutsch] [Español] [Italiano] [Français] [日本語] [한국어] [中文]

**Comment by jamescummings** [comment] 2017-06-26 10:04
I've done 1) by adding an English example (from the chapter prose) to the spec file at https://github.com/TEIC/TEI/commit/a32b392fbe8facc78328c291cce9c2aac459799c 

Leaving open as a reminder why we want to do https://github.com/TEIC/Stylesheets/issues/273

Otherwise we should remove all exemplum which do not have one of these languages.

**Comment by jamescummings** [comment] 2017-06-26 13:21
council suggests closing this since stylesheets ticket is open

**Closed by jamescummings** 2017-06-26 13:21 UTC
Labels: Status: Go
