### ISSUE TITLE
The Debian packages cannot be downloaded

### ISSUE THREAD

**Issue by lddubeau** [TEIC/TEI#1913] opened 2019-08-21 14:50 UTC
I have a Docker build that performs a TEI installation on a Debian image. It uses https://packages.tei-c.de/deb/binary as the source for the TEI packages. However,  the DNS name `packages.tei-c.de` does not resolve. I've been able to run builds for the past few weeks without issues, so this seems to be a relatively new failure.

I did not see any post on TEI-L concerning this (e.g. mentioning scheduled downtime, or that we should use another site). Maybe someone needs to be informed about the problem?

It seems the whole `tei-c.de` domain is not resolving right now.

I checked https://tei-c.org/, and that page still lists `packages.tei-c.de` as the place to get the Debian packages.

**Comment by peterstadler** [comment] 2019-08-21 15:19
Hi @lddubeau 
that is strange, it does work for me (just tested in a fresh Docker container).

We had some hiccups this morning (GMT+1) due to maintenance work but all should be ok for at least several hours.

For the record: both domains (packages.tei-c.de and packages.tei-c.org) point at the same server right now: 
```bash
# ping packages.tei-c.de
PING packages.tei-c.de (193.175.67.196) 56(84) bytes of data.
64 bytes from muwi.hfm-detmold.de (193.175.67.196): icmp_seq=1 ttl=37 time=0.568 ms 
```

```bash
# ping packages.tei-c.org
PING packages.tei-c.org (193.175.67.196) 56(84) bytes of data.
64 bytes from muwi.hfm-detmold.de (193.175.67.196): icmp_seq=1 ttl=37 time=0.625 ms
```

So, I recommend to switch back to the primary address (which we should change on the website as well)

**Comment by lddubeau** [comment] 2019-08-21 15:53
Here's what I get:

```
$ ping packages.tei-d.org
ping: packages.tei-d.org: Name or service not known
```

```
$ ping packages.tei-c.org
PING packages.tei-c.org (193.175.67.196) 56(84) bytes of data.
^C
--- packages.tei-c.org ping statistics ---
54 packets transmitted, 0 received, 100% packet loss, time 303ms
```

This ping just hangs there so I have to use Ctrl-C to end it. The DNS name is resolved but the ping is not answered.

I can access all other sites external to my network without any issue. My observations above are from a location in Frederick, MD. Just in case I'm running into some weird routing corruption, I logged into a server hosted by Linode in Newark, NJ. I get the same results there. I also tried on my phone, using my cell provider's network, and get the same result.

----

But the above is a bit theoretical now. If I put `https://packages.tei-c.org` in my browser, I get a 50x error, but this indicates there is a site responding to that address. I modified one of my apt sources file to use the full URL `deb https://packages.tei-c.org/deb/binary ./`. This works.

I know from looking at my bash history that I did try `ping packages.tei-c.org` prior to posting this issue but I don't remember whether I just got a lack of ping reply or whether the DNS was also problematic. Still, the lack of ping reply made it look like there was an actual network issue, and I did not investigate further since at that time, https://tei-c.org/ was still pointing people to the `de` site, which had been the status quo for a long time. So yeah, from my point of view it was to be expected that `packages.tei-c.org` wouldn't work.

I see https://tei-c.org/ has been edited to change the link so as far as I'm concerned this can be closed.

**Comment by martindholmes** [comment] 2019-08-21 15:59
Confirmed that pinging packages.tei-c.de from here (Canada) fails.

**Comment by peterstadler** [comment] 2019-08-21 16:34
ok, right, our firewall drops external ICMP requests, so there's nothing to expect from `ping`. Another caveat is that there is no web server listening on `https://packages.tei-c.org` directly but only on the  `/deb/` subfolder. 

Yet, the Debian packages are available from both domains – as confirmed by @lddubeau – (and the link from tei-c.org is updated to point at the main one) so I'm closing the issue.

**Closed by peterstadler** 2019-08-21 16:34 UTC
