### ISSUE TITLE
fallout from @toWhom

### ISSUE THREAD

**Issue by sydb** [TEIC/TEI#1794] opened 2018-07-20 15:33 UTC
@scstanley7 and I were working on #1679, and in doing so came across several issues that should be addressed. I am collecting them here just for convenience.

1. The 2nd of the two "DSHD-eg-30" examples in CO has a completely superfluous `<namespace>` and `@xml:id`s.
1. The 1st of the three "COHQQ-eg-23" examples in CO points to a list of empty items!
1. Pointing from `@who` (and `@toWhom`) to a `<person>` should at least be mentioned, if not exemplified, no?

**Comment by sydb** [comment] 2018-07-20 15:36
(1), above, fixed at 70363c7.

**Comment by ebeshero** [comment] 2018-07-20 16:40
I'm self-assigning this because I'd like to try encoding an aside from one of the plays we're working on, using `@toWhom`. Re (2) above, note that the problem is in the *third* of the three "COHQQ-eg-23" examples.

**Comment by ebeshero** [comment] 2019-01-17 22:39
Keeping open a moment. With https://github.com/TEIC/TEI/commit/6905d111cd0373a4b69697cabe071820f8017e30, I altered example 3 of COHQQ-eg-23 to do the following: 

* Apply an example of `@toWhom` together with `@who`
* use abbreviated reference values for the speakers (to demonstrate these don't have to be identical to full names)
* use `<listPerson>` and `<person>` as in a personography instead of `<list>` with `<item>`.

**Comment by ebeshero** [comment] 2019-01-18 03:41
Closing b/c Mr. Jenkins is happy, and the edits address (2) and (3) above.

**Closed by ebeshero** 2019-01-18 03:41 UTC
