### ISSUE TITLE
Readme in release points to the wrong version of P5

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1444] opened 2016-04-04 12:41 UTC
If you go here:

http://www.tei-c.org/Vault/P5/current/doc/tei-p5-doc/readme-2.8.0.html

and click on "this release", you'll go to the current release, not 2.8.0. The same is true for 2.9.1. I haven't checked any other readmes yet.

**Comment by jamescummings** [comment] 2016-04-04 12:50
Confirmed.  I think this is just lazy release-note writing, copying the previous release notes to this one. It starts in version 2.6.0 from what I can tell and is present in: 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1 and 3.0.0.

I'll go back and edit the URLs in these past release notes.

Assigning to me, marking green.

**Comment by jamescummings** [comment] 2016-04-04 13:55
I have changed these in dev branch (and a couple mistakenly in master, oops) and the 3.0.0 one in master (because it wasn't in dev).  I have handedited the readme*.html files for 2.6.0 - 3.0.0 on the tei-c.org server and then back-copied them to the correct directories.  All should now point to the correct version of the text when they say 'this release' rather than the current version.

**Closed by jamescummings** 2016-04-04 13:55 UTC
Labels: Priority: Medium, Status: Go, TEI: Website, Type: Bug
