### ISSUE TITLE
teidata.points could be more tightly constrained

### ISSUE THREAD

**Issue by martindholmes** [TEIC/TEI#1727] opened 2017-12-08 16:38 UTC
Arising out of the work on #1453, @sydb and I are looking at the definition of teidata.point, and it looks like this:
~~~~~
<desc versionDate="2010-10-17" xml:lang="en">defines the data type used to express a point in cartesian space.</desc>
  <content>
      <dataRef name="token" restriction="(\-?[0-9]+\.?[0-9]*,\-?[0-9]+\.?[0-9]*)"/>
   </content>
~~~~~

This allows for leading zeroes and trailing zeroes after decimal points; it also allows a decimal point with no following digits. We believe it would be better to rewrite the regex so that it does not allow any of these variants, so that checking the identity of two sets of coordinates (which we have to do in other places in Schematron) would be easier, and coordinates would be more consistently expressed.

**Comment by sydb** [comment] 2017-12-08 16:46
A regexp that would disallow leading and trailing zeroes:
~~~~~xml
<content>
 <dataRef name="token"
  restriction="(-?([1-9][0-9]*|0)(\.[0-9]+[1-9])?,-?([1-9][0-9]*|0)(\.[0-9]+[1-9])?)"/>
</content>
~~~~~
(And note I’ve removed the extraneous backslash at the beginning.)

**Comment by sydb** [comment] 2017-12-08 21:30
Just to make my position clear: I think that teidata.point should enforce the common sense rule of thumb that if there is a decimal point (and we’ve already committed to using dot as the decimal indicator, not comma), there should be at least one digit on either side of it. (Section 10.5.2 of NIST SP811 addresses that there should be a digit to the left; it does not actually say there has to be a digit to the right, but values like “17.” seem like a very bad idea.)

As to whether the teidata.point datatype should prohibit leading and trailing zeroes, I’m on the fence. Martin is thinking that this would make processing the points easier, and I think he is right. But it’s not all that much harder to convert the values to numbers before comparison (see below), and another point (pardon the pun) has occurred to me: the coordinate expressions `"41.827000,-71.400000"` and `"41.827,-71.400"` do not mean exactly the same thing: the former is precise to roughly a meter, the latter to only roughly a kilometer.

(BTW, in case anyone is wondering, those coordinates are at the rear door to the Brown University Sciences Library.)

Here is one way to do the test converting to numeric values first.
~~~~~xml
    <sch:rule context="tei:*[@path]">
      <!--
        Note: this is being fired an *all* @path attrs, not just those
        inherited from att.coordinated. (At the moment, there are no
        others, so it doesn't matter.)
      -->
      <sch:let name="firstPair" value="tokenize( normalize-space( @path ), '&#x20;')[1]"/>
      <sch:let name="lastPair"  value="tokenize( normalize-space( @path ), '&#x20;')[last()]"/>
      <sch:let name="firstLat"  value="xs:float( substring-before( $firstPair, ',') )"/>
      <sch:let name="firstLong" value="xs:float( substring-after( $firstPair, ',') )"/>
      <sch:let name="lastLat"   value="xs:float( substring-before( $lastPair, ',') )"/>
      <sch:let name="lastLong"  value="xs:float( substring-after( $lastPair, ',') )"/>
      <sch:report test="$firstLat eq $lastLat  and  $firstLong eq $lastLong">The first and
        last elements of your path are the same. If you want to specify a closed polygon, use
        @points rather than @path. </sch:report>
    </sch:rule>
~~~~~

**Comment by martindholmes** [comment] 2017-12-08 22:09
I think it makes much more sense to constrain the datatype in the first place. Why would we allow a variety of expressions which are numerically equivalent but arbitrarily variant? There's no benefit to anyone from that. And the regex in my original Schematron (which triggered this issue):

https://github.com/TEIC/TEI/blob/mdh_path_1453/P5/Source/Specs/att.coordinated.xml#L90

is way simpler and will run way more quickly; which is important when a document may contain hundreds of instances of coordinates.

**Comment by sydb** [comment] 2017-12-09 17:03
> Why would we allow a variety of expressions which are numerically equivalent but arbitrarily variant?

Because the difference is not arbitrary. `path="41.827000,-71.400000 41.826982,-71.392148"` gets to be drawn with a much narrower line than `path="41.827,-71.4 41.826982,-71.392148"`, as it were.


> And the [original proposed string-comparison] regex … will run way more quickly

Actually (to my surprise), that turns out not to be the case. I wanted to see _how much_ faster the string comparison was over the convert to numbers method. So I just ran an empirical test (details below), and kinda shockingly found that the numerical method is a teeny bit faster:

|     | string | numerical |
|-----|--------|-----------|
| real	| 2m2.943s | 2m0.850s 
|user	|3m50.228s  |  3m43.212s
|sys	|1m18.580s  |  1m16.680s

I find that so surprising, I wonder if I did something wrong. I’m hoping others will reproduce the experiment, preferably with different Schematron processors.

1. I created the two Schematron test files (sorry, I don’t know how to make sub-numbered lists in GitHub flavored Markdown):
1. copied the Schematron from [mdh_path_1453]/P5/Source/Specs/att.coordinated.xml into [latLongLoopCheck_string](http://paramedic.wwp.northeastern.edu/~syd/temp/TEI_Council/ticket1727/latLongLoopCheck_string.sch)
 1. copied the code [above](https://github.com/TEIC/TEI/issues/1727#issuecomment-350376978) into [latLongLoopCheck_numeric](http://paramedic.wwp.northeastern.edu/~syd/temp/TEI_Council/ticket1727/latLongLoopCheck_numeric.sch)
1. Created a large [test file](http://paramedic.wwp.northeastern.edu/~syd/temp/TEI_Council/ticket1727/lotsaLatLongLoops.xml) that has 1024 `<zone>` elements, each with a `@path` that has 1000 pairs of coordinates. (Yeah, I know, I’m mixing my bases.)
1. Ran each of the two Schematron files against the test file 100 times in a row using `probatron` in a shell in an Emacs buffer. (That’s only important because output is *much* slower when you’re in an Emacs buffer. But since there wasn’t much output, and it was the same, this isn’t a problem; it just explains why you might get faster results if you try this on a similar machine in a Terminal window. The machine I used has an Intel® Core™ i7-4790K CPU @ 4.00GHz.)

**Comment by hcayless** [comment] 2017-12-09 17:44
Doesn’t surprise me a bit. String comparison is quite a bit more involved than numeric comparison in Java (really in most, if not all languages).

**Comment by martindholmes** [comment] 2017-12-09 23:21
@sydb 

>  path="41.827000,-71.400000 41.826982,-71.392148" gets to be drawn with a much narrower line than path="41.827,-71.4 41.826982,-71.392148", as it were.

Drawn by what system, where? -71.400000 is identical to -71.4 numerically, and unless a particular codebase is specialized in order to interpret trailing zeroes in a particular way, they don't mean anything different. A pure line has no width, otherwise it's a shape.

But the speed argument is quite convincing, so I've included your rule in place of mine. Thanks!

**Comment by martindholmes** [comment] 2017-12-09 23:23
Also, @sydb, it occurs to me that your argument about points on a path is based on GIS coordinates, but att.coordinated attributes are not intended for that; they're for coordinates on a surface. You'd use `<geo>` for GIS, with a standard scheme such as the GeoJSON coordinate system.

**Comment by sydb** [comment] 2017-12-15 16:42
Hi @martindholmes. I find your argument [two posts ago](https://github.com/TEIC/TEI/issues/1727#issuecomment-350512697) pretty unconvincing, but your argument in the [previous post](https://github.com/TEIC/TEI/issues/1727#issuecomment-350512798) completely convincing. My mental slip-up was to be using latitude and longitude as the coordinate space, where in truth it is the coordinate space defined on the parent `<surface>` that we are talking about. And thinking about it, why would you ever need to address a space you invented with fractional coordinates? Hmmm… 

(All: @martindholmes agrees, and has just posted that very question to [TEI-L](https://listserv.brown.edu/?A2=ind1712&L=tei-l&F=&S=&P=29949) about.)

**Comment by ebeshero** [comment] 2018-02-25 17:23
F2F discussion: we don't think this is a good idea--we don't want to constrain leading and trailing zeroes.

**Comment by peterstadler** [comment] 2018-02-25 17:41
My take on this: 
```
(-?[0-9]+(\.[0-9]+)?,-?[0-9]+(\.[0-9]+)?)
```

**Comment by sydb** [comment] 2018-02-26 00:39
> we will constrain such that decimals MUST be followed by a digit.

Deprecation set up at 0862be5.

**Closed** 2018-04-24 21:11 UTC
Labels: Status: Go
