### ISSUE TITLE
broken links to non-English bibliography entries from examples-* pages

### ISSUE THREAD

**Issue by peterstadler** [TEIC/TEI#2106] opened 2021-02-11 15:22 UTC
While refactoring our Linkchecker Jenkins job I came across various internal references to missing entries in the bibliography from some examples-* pages. Turns out the references are to non-english entries in the bibliography, e.g. the first example on  https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/examples-condition.html which links to the "bibliography"  like 
```html
<a href="javascript:void(0)" onclick="showPopupBibl('fr-ex-BnF-Reliures')">bibliography</a>
```

Yet, the target "fr-ex-BnF-Reliures" is only declared in the french section of the bibliography and unavailable to the english HTML version.
https://github.com/TEIC/TEI/blob/efeb3baae510141c70fc497e699a4d4c13df2029/P5/Source/Guidelines/en/BIB-Bibliography.xml#L1031

Quick searching in the TEI and the Stylesheets repo showed some related tickets (#1476, https://github.com/TEIC/Stylesheets/issues/173), yet I didn't find a description of this particular issue.

**Comment by martindholmes** [comment] 2021-02-11 16:18
The JavaScript there is misleading; in fact in the source it's a regular link:

`<a href="BIB.html#fr-ex-BnF-Reliures">bibliography</a>`

which is converted into a popup call on load, if JS is enabled. The problem is either:

 - The examples pages themselves should not include examples from other languages than the current one; or
 - The bibliography should include all language items, whatever the current GL build language is; or
 - Examples from other languages should not have bibl links attached to them; or
 - Examples in other languages should link to the bibliography of the other language (potentially quite confusing, I think).

I think I favour the second.

**Comment by hcayless** [comment] 2021-02-15 14:19
I think the ideal would be a single bibliography that was able to handle works in multiple languages (so if there are both English and French versions of a book, e.g.), they would both be listed under the same heading. I haven't looked at all at what might be involved in making that work...

**Comment by ebeshero** [comment] 2021-12-09 19:59
On Council discussion today (2021-12-09), this is green for @HelenaSabel to check to see if we have any examples of a `<bibl>` resource expressed in multiple languages, and if we do, to try to merge them into one entry. Move the `@xml:lang` into the freshly merged `<bibl>` then.

**Comment by ebeshero** [comment] 2021-12-09 20:04
Amended: On Council discussion today (2021-12-09), this is green for @HelenaSabel to check to see if we have any examples of a `<bibl>` resource expressed in multiple languages, and if we do, to try to merge them into one `<listBibl>`. Move the `@xml:lang` into the freshly merged `<bibl>` then.

**Closed as completed** 2022-04-19 11:33 UTC
Labels: Type: Bug, Status: Go
