### ISSUE TITLE
att.citing - values of @unit

### ISSUE THREAD

**Issue by emmamorlock** [TEIC/TEI#1696] opened 2017-10-17 15:48 UTC
Hi
I was looking for the schema for the attribute @issue because in oxygen the value "entry" was not presented to me (even after updating the TEI framework).
So I went to https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/att.citing.xml 
Isn't there some kind of inversion in <desc> elements between "column" and "entry" ? (and also for my instruction: why don't I get them in Oxygen?)

```
<valItem ident="column">
	  <desc versionDate="2013-06-17" xml:lang="en">the element identifies an entry number or label in a list of entries.</desc>
	</valItem>
```
```
        <valItem ident="entry">
          <desc versionDate="2017-06-24" xml:lang="en">the element identifies a column.</desc>
        </valItem>
```

**Comment by martinascholger** [comment] 2017-10-18 19:09
Just to be sure, do you refer to the attribute `@unit`, since 'issue' is acutally a value of `@unit` (just like 'column' and 'entry')? 
Thanks for pointing out the interchanged descriptions.

**Comment by emmamorlock** [comment] 2017-10-19 12:54
yes it's `@unit.`
eg 
```
<citedRange unit="entry">xxxxxx</citedRange> 
<citedRange unit="column">5</citedRange> 
```

**Comment by martindholmes** [comment] 2017-10-19 16:20
This looks like a straightforward copy-paste error; someone adding a new item perhaps copy-pasted an existing one, then put the new definition in the wrong one. It looks like @ebeshero added the new item in commit 6ff58d3d465de19176ff14aa13600cd903c84038 dealing with ticket #1555 -- Elisa, could you check and see if I'm right?

**Comment by martinascholger** [comment] 2017-10-31 08:32
It was just a copy-paste error, fixed in #1696. @emmamorlock: does the problem still exist, that you don't get the 'entry' in the value list? I cannot reproduce it, since it works in my (updated) version.

**Comment by ebeshero** [comment] 2017-10-31 11:20
Thanks for fixing this,  @martinascholger ! Sorry I missed seeing the notification from @martindholmes earlier—I am only seeing it now.

**Comment by emmamorlock** [comment] 2017-11-03 15:12
Hello Marina,  I get the 'entry' value now (updated to oXygen 19.1).
Thanks

**Comment by martinascholger** [comment] 2017-11-03 17:08
Great!

**Closed by martinascholger** 2017-11-03 17:08 UTC
Labels: Status: Go, TEI: Guidelines & Documentation
