### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by wobweger** [TEIC/TEI#2009] opened 2020-06-24 12:02 UTC
dear all,

I'm new at this, so please pardon me.
I tried to locate and follow build [instructions](https://tei-c.org/guidelines/p5/using-the-tei-github-repository/).

stylesheet tests seem to work. at least `Stylesheets/Test/test_xml.odt` has current date and looks okay.

checking log (a lot) show warnings `XML resolver not found`.
is that an indication of a bigger problem?

[20200624.log](https://github.com/TEIC/TEI/files/4825189/20200624.log)

here is what I managed to achieve on CentOS 8 `Prerequisites for use of TEI Modules`

### install tools

```
yum install ant
yum install perl
```

failed on centOS 8

+ jing 
+ saxon
+ trang
  + [relaxng](https://relaxng.org/jclark/trang.html)
  + [https://relaxng.org/jclark/trang-manual.html](https://relaxng.org/jclark/trang-manual.html)
+ xmllint
  already installed on centOS 8
+ xsltproc
  already installed on centOS 8

found repo [jing-trang](https://github.com/relaxng/jing-trang.git)

thx for any additional instructions in advance.

**Comment by sydb** [comment] 2020-06-24 13:38
Have a meeting in -8 mins, so can’t dive into details now. But 1st question: are you trying to build the Stylesheets, the _Guidelines_, or both, and why?
Generally speaking if you want to build a local copy of the _Guidelines_, it is a lot easier to do with a container. (We use Docker.) Instructions are ... um, I will look around for them.
In the meantime, I am not much of a CentOS user, but can verify I do have xmllint, xsltproc, and perl already installed. My vague recollection is you would have to install jing-trang, ant, and saxon on your own.

**Comment by sydb** [comment] 2020-06-24 13:59
We have two kinds of Docker images for building the _Guidelines_. The first was originally intended to set up a CI server as well, but can be used without, for which there is [some documentation](https://github.com/TEIC/Jenkins#usage-of-the-docker-image-without-the-jenkins-server).
The second is, I think, intended to be used for building the development version (as opposed to released version) of the _Guidelines_, but I bet it is not hard to change to released instead. Documentation is available [off the GitHub repo](https://github.com/TEIC/teidev-docker).
Both of these should be considered experimental with limited support. That said, their respective authors are pretty responsive.

**Comment by sydb** [comment] 2020-06-24 14:02
Oh, and no, I don’t think the “XML resolver not found” messages are a problem at all.

**Comment by wobweger** [comment] 2020-06-24 14:12
thx, for you response.
I'll go through answers in detail, when my brain is back to operation, so tomorrow morning.

I guess, I don't want to build guidelines locally.
Having TEI ready to use locally, I want.
Getting a good looking document (LaTex, pdf) out of encoded xml is useful.
(just started to walk learning curve :wink:)

**Comment by sydb** [comment] 2020-06-24 14:20
Then I think you probably already have what you need (a copy of the Stylesheets repo).

To use, try something like
```bash
$ /place/where/you/put/TEIC/Stylesheets/repo/bin/teitolatex /path/to/your/INPUT.tei
```
That will produce a file /path/to/your/INPUT.tei.latex. Whether it is good looking or not is another story. There are converts to docx, epub, html, and pdf, among others. These do pretty much exactly the same conversion as you get in oXygen or [OxGarage](https://oxgarage.tei-c.org/).

**Comment by wobweger** [comment] 2020-06-25 05:12
@sydb thx for your fast response :smile: 

+ teitolatex
+ teitohtml
+ teitohtml5

all work fine, properly installed, so shell command  
`teitohtml asj18930310.xml `  
produce an good looking result.

[input](https://schnitzler-tagebuch.acdh.oeaw.ac.at/resolver/resolve-doc.xql?doc-name=entry__1893-03-10.xml&collection=editions)
[online](https://schnitzler-tagebuch.acdh.oeaw.ac.at/pages/show.html?document=entry__1893-03-10.xml)

+ tetodocx throw an error

```
[wal@sokrates 0_TEI]$ teitodocx asj18930310.xml 
WARNING: No localsource set. Will get a copy from https://www.tei-c.org/Vault/P5/current/xml/tei/odd/p5subset.xml if necessary.
Convert asj18930310.xml to /home/wal/gitlab/wroacdhitp20203/0_gen/0_TEI/asj18930310.xml.docx (tei to docx) using profile default
Warning: XML resolver not found; external catalogs will be ignored
Warning: XML resolver not found; external catalogs will be ignored

BUILD FAILED
/usr/share/xml/tei/stylesheet/docx/build-to.xml:35: The following error occurred while executing this line:
/usr/share/xml/tei/stylesheet/common/teianttasks.xml:177: Fatal error during transformation using /usr/share/xml/tei/stylesheet/profiles/default/docx/to.xsl: Cannot execute xsl:result-document while evaluating xsl:variable; SystemID: file:/usr/share/xml/tei/stylesheet/docx/to/headers.xsl; Line#: 106; Column#: 88

Total time: 16 seconds
```
informed curators also.

so far I'm completely overjoyed :smiley:   
merci.

(just figured; latex is missing yet)

**Comment by sydb** [comment] 2020-06-25 14:32
Error confirmed.
Taking a look now. I can not even find the problem, let alone figure out what to do about it.

- symlink `teitodocx` calls `transformtei`
- it calls ant using docx/build-to.xml
- it calls `<builddocx>`, which is defined in common/teianttasks.xml
- on line 177 it tries to process profiles/default/docx/to.xsl with Saxon
- to.xsl imports docx/to/teitodocx.xsl
- docx/to/teitodocx.xsl includes (among lots of other things) docx/to/headers.xsl
- that file has a template "write-docxfile-specific-header-file"
- it is called from only 1 template, namely "write-docxfile-header-files" in the same file
- it is called from only 2 templates, one in docx/to/teitodocx.xsl (the other in profiles/iso/docx/to.xsl which I do not think has anything to do with this case)
- that call in teitodocx.xsl (on line ~337) is from named template "write-docxfiles"
- it is also only called once, from line ~318 in the same file, from within the template that matches the document node
- that call does **not** appear to me to be inside an `<xsl:variable>` (I must be missing something)

All of three of these templates ("write-docxfiles", "write-docxfile-header-files", and "write-docxfile-specific-header-file") are named, none has a `@match` let alone `@mode`. So they are only being called with `<call-template>`, right? But I see no `<variable>` definitions in the call sequence. The "write-docxfiles" is called from a `<for-each>` that iterates over the result of 'pass0', which (it turns out) is just a a copy of the input file. I.e., that template is called after the context node is set to a copy of the input `<TEI>` element. No variables that I see, though. Harrumph.

**Comment by sydb** [comment] 2020-06-25 14:56
Another approach we might take: what is different about @wobweger’s input file here such that it throws this error, whereas other people have (I presume) been using teitodocx for years without a problem.
I’m running teitodocx on a selection of ~30 TEI files chosen at whim, just to see what happens.
Roughly 1 of 3 “Failed to process”, including at least one case of a similar error in a different place. This is weird. Have a meeting in 3 mins, but may try to take another run at this later.

**Comment by peterstadler** [comment] 2020-06-25 15:25
There are [some known issues with the docx transformation](https://github.com/TEIC/Stylesheets/issues?q=is%3Aissue+is%3Aopen+label%3A%22conversion%3A+docx%22), especially when dealing with documents from GoogleDocx.

**Comment by wobweger** [comment] 2020-06-25 15:34
credit goes to @martinantonmueller :smile:

**Comment by sydb** [comment] 2020-06-26 17:48
@wobweger: just curious, credit for what goes to @martinantonmueller? (TEI file says Index collation and corrections.)

Also, what was the problem you were having with LaTeX output? (I ran the output through a program to render the LaTeX as HTML. It found an extraneous ampersand (‘&’) on line 338; after I removed that, same program gave no errors, but also ran forever and gave no results. :-(

Anyway, you have stumbled across at least two problems:

- The [TEI: Using the TEI GitHub Repository](https://tei-c.org/guidelines/p5/using-the-tei-github-repository/) document needs some work (this ticket)
- teitodocx throws an error (apparently when an `@ref` points to a `<person>` that is not in the `<particDesc>`, but more testing is needed) — this is now [Stylesheets ticket #445](https://github.com/TEIC/Stylesheets/issues/445).

**Comment by martinantonmueller** [comment] 2020-06-26 18:43
I don‘t know what I am doing here, either!

**Comment by wobweger** [comment] 2020-06-29 07:16
finding good test data is and has been always a challenge, I as a coder was and will be always happy once I've got one.
but never mind.

back to latex then, current version on centOS8 gives me a headache 
`texlive.x86_64                    7:20180414-14.el8 `
properly my skills are a little rusty

so far I had to install 

```shell
yum install texlive-fancyhdr
yum install texlive-fonts-recommended
```

and add several packages

+ wrapfig
+ relsize
+ ucs
+ framed
+ ulem

now I've reached a dead end

+ eledmac, doesn't make because babel doesn't know english

```shell
[root@sokrates eledmac]# ls
eledmac.dtx  eledmac.pdf  eledpar.ins  examples   Makefile
eledmac.ins  eledpar.dtx  eledpar.pdf  latexmkrc  README
[root@sokrates eledmac]# make
rm -f eledmac.sty eledmactex
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./eledmac.ins
LaTeX2e <2017-04-15>
Babel <3.17> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/docstrip.tex
Utility: `docstrip' 2.5e <2014/09/29>
English documentation    <2017/03/13>

**********************************************************
* This program converts documented macro-files into fast *
* loadable files by stripping off (nearly) all comments! *
**********************************************************

********************************************************
* No Configuration file found, using default settings. *
********************************************************

(./eledmac.ins
*** Generating the LaTeX2e package files ***

Generating file(s) ./eledmac.sty 

Processing file eledmac.dtx (code) -> eledmac.sty
File eledmac.dtx ended by \endinput.
Lines  processed: 16847
Comments removed: 10641
Comments  passed: 5
Codelines passed: 6197

*** Generating the LaTeX2e example files ***
***********************************************************
*
* To finish the installation you have to move the following
* file(s) into a directory searched by LaTeX. See the FAQ on
* CTAN at /help/uk-tex-faq for more on this.
*
*   eledmac.sty
*
*
* To produce the documentation run the files ending with
* `.dtx' through LaTeX.
* For an index, process any name.idx file by:
*     makeindex -s gind.ist name
* For a list of changes, process any name.glo file by:
*     makeindex -s gglo.ist -o name.gls name.glo
*
* Happy TeXing
***********************************************************
) ) )
No pages of output.
Transcript written on eledmac.log.
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./eledmac.dtx
LaTeX2e <2017-04-15>
Babel <3.17> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/ltxdoc.cls
Document Class: ltxdoc 2017/03/13 v2.0v Standard LaTeX documentation class
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/doc.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/multicol.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg))

Package hyperref Message: Driver (autodetected): hxetex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/tuenc.def))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/switch.def)

! Package babel Error: Unknown option `english'. Either you misspelled it
(babel)                or the language definition file english.ldf was not foun
d.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.434 \ProcessOptions*
                      
? 

! Package babel Error: You haven't specified a language option.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.467 ...ry to proceed from here, type x to quit.}
                                                  
? quit
OK, entering \batchmodemake: *** [Makefile:26: eledmac.pdf] Error 1
```
I looked into `/usr/share/texlive/texmf-dist/tex//generic/babel` and a lot of languages `.sty` are present.
`duckduck` going point always to https://latex.org/ but firefox is resisting any connection attempt.

![tei_20200629_latex_babel_0](https://user-images.githubusercontent.com/40311784/85983802-6e29b600-b9e8-11ea-9df2-bd4c3cd1d57c.png)
![tei_20200629_latex_babel_1](https://user-images.githubusercontent.com/40311784/85983816-74b82d80-b9e8-11ea-9dca-b94e02522a88.png)

all of that I tried on `test.xml` (in some TEI repo, Stylesheet of P5), which looks harmless enough.

```xml
<TEI  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>The title</title>
      </titleStmt>
      <publicationStmt>
        <p/>
      </publicationStmt>
      <sourceDesc>
        <p/>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p rend="foo bar"><app><lem wit="#El">earth</lem><rdg>mud</rdg></app></p>
    </body>
  </text>
</TEI>
```

**Comment by sydb** [comment] 2020-06-29 07:23
Sorry, @wobweger, I do not know anything about installing LaTeX. But that URL (the [LaTeX Forum](https://latex.org/forum/)) loaded fine for me, so I would encourage you to try again.

**Comment by lb42** [comment] 2020-06-29 17:53
did you install the texlive-xetex package?

**Comment by wobweger** [comment] 2020-06-30 06:29
yes `texlive-xetex.x86_64                7:20180414-14.el8`

**Comment by martindholmes** [comment] 2020-07-22 16:46
@wobweger I'm not quite clear on what the problem is here. Could you post the TEI file you're trying to convert, and explain exactly what you see when you run teitolatex on it? Also, do you have the texlive-full package installed? Grepping my texlive packages, I have these:

texlive-base/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-bibtex-extra/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-binaries/bionic-updates,bionic-security,now 2017.20170613.44572-8ubuntu0.1 amd64 [installed,automatic]
texlive-extra-utils/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-font-utils/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-fonts-extra/bionic,bionic,now 2017.20180305-2 all [installed]
texlive-fonts-extra-doc/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-fonts-extra-links/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-fonts-recommended/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-fonts-recommended-doc/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-formats-extra/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-full/bionic,bionic,now 2017.20180305-1 all [installed]
texlive-games/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-generic-recommended/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-humanities/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-humanities-doc/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-lang-arabic/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-chinese/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-cjk/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-cyrillic/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-czechslovak/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-english/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-european/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-french/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-german/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-greek/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-italian/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-japanese/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-korean/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-other/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-polish/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-portuguese/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-lang-spanish/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-latex-base/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-latex-base-doc/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-latex-extra/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-latex-extra-doc/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-latex-recommended/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-latex-recommended-doc/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-luatex/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-metapost/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-metapost-doc/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-music/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-pictures/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-pictures-doc/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
texlive-plain-generic/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-pstricks/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-pstricks-doc/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-publishers/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-publishers-doc/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-science/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-science-doc/bionic,bionic,now 2017.20180305-2 all [installed,automatic]
texlive-xetex/bionic,bionic,now 2017.20180305-1 all [installed,automatic]

(This is on Ubuntu 18.04). Not saying they're all needed, of course, just that that's what I have.

**Comment by ebeshero** [comment] 2020-07-22 16:51
Hi @martindholmes ! I was triaging tickets and thought you just might have some ideas about this one! :-) Thanks for jumping in.  @wobweger, I take it you are still having difficulties, right?

**Comment by wobweger** [comment] 2020-07-23 04:39
no progress to report so far, still lost in LaTeX administration

2 suspicious facts may need resolving:

+ package babel doesn't know english
+ eledmac / reledmac or so doesn't build
  got the impression this package is important

what's installed :arrow_down: , in addition some TeX packages were added manually

```bash
[root@sokrates lindworm]# yum list installed
Installed Packages
texlive-algorithms.noarch                  7:20180414-14.el8          @AppStream
texlive-amsfonts.noarch                    7:20180414-14.el8          @AppStream
texlive-amsmath.noarch                     7:20180414-14.el8          @AppStream
texlive-attachfile.noarch                  7:20180414-14.el8          @AppStream
texlive-avantgar.noarch                    7:20180414-14.el8          @AppStream
texlive-babel.noarch                       7:20180414-14.el8          @AppStream
texlive-babelbib.noarch                    7:20180414-14.el8          @AppStream
texlive-base.noarch                        7:20180414-14.el8          @AppStream
texlive-bera.noarch                        7:20180414-14.el8          @AppStream
texlive-bibtex.x86_64                      7:20180414-14.el8          @AppStream
texlive-bookman.noarch                     7:20180414-14.el8          @AppStream
texlive-booktabs.noarch                    7:20180414-14.el8          @AppStream
texlive-breakurl.noarch                    7:20180414-14.el8          @AppStream
texlive-caption.noarch                     7:20180414-14.el8          @AppStream
texlive-carlisle.noarch                    7:20180414-14.el8          @AppStream
texlive-charter.noarch                     7:20180414-14.el8          @AppStream
texlive-chngcntr.noarch                    7:20180414-14.el8          @AppStream
texlive-cm.noarch                          7:20180414-14.el8          @AppStream
texlive-cm-super.noarch                    7:20180414-14.el8          @AppStream
texlive-cmextra.noarch                     7:20180414-14.el8          @AppStream
texlive-collection-basic.noarch            7:20180414-14.el8          @AppStream
texlive-collection-fontsrecommended.noarch 7:20180414-14.el8          @AppStream
texlive-colortbl.noarch                    7:20180414-14.el8          @AppStream
texlive-courier.noarch                     7:20180414-14.el8          @AppStream
texlive-csquotes.noarch                    7:20180414-14.el8          @AppStream
texlive-currfile.noarch                    7:20180414-14.el8          @AppStream
texlive-dvipdfmx.x86_64                    7:20180414-14.el8          @AppStream
texlive-dvips.x86_64                       7:20180414-14.el8          @AppStream
texlive-ec.noarch                          7:20180414-14.el8          @AppStream
texlive-enctex.noarch                      7:20180414-14.el8          @AppStream
texlive-enumitem.noarch                    7:20180414-14.el8          @AppStream
texlive-eso-pic.noarch                     7:20180414-14.el8          @AppStream
texlive-etex.noarch                        7:20180414-14.el8          @AppStream
texlive-etex-pkg.noarch                    7:20180414-14.el8          @AppStream
texlive-etoolbox.noarch                    7:20180414-14.el8          @AppStream
texlive-euro.noarch                        7:20180414-14.el8          @AppStream
texlive-eurosym.noarch                     7:20180414-14.el8          @AppStream
texlive-fancyhdr.noarch                    7:20180414-14.el8          @AppStream
texlive-fancyvrb.noarch                    7:20180414-14.el8          @AppStream
texlive-filecontents.noarch                7:20180414-14.el8          @AppStream
texlive-filehook.noarch                    7:20180414-14.el8          @AppStream
texlive-float.noarch                       7:20180414-14.el8          @AppStream
texlive-fontspec.noarch                    7:20180414-14.el8          @AppStream
texlive-footmisc.noarch                    7:20180414-14.el8          @AppStream
texlive-fp.noarch                          7:20180414-14.el8          @AppStream
texlive-fpl.noarch                         7:20180414-14.el8          @AppStream
texlive-geometry.noarch                    7:20180414-14.el8          @AppStream
texlive-glyphlist.noarch                   7:20180414-14.el8          @AppStream
texlive-graphics.noarch                    7:20180414-14.el8          @AppStream
texlive-graphics-cfg.noarch                7:20180414-14.el8          @AppStream
texlive-graphics-def.noarch                7:20180414-14.el8          @AppStream
texlive-gsftopk.x86_64                     7:20180414-14.el8          @AppStream
texlive-helvetic.noarch                    7:20180414-14.el8          @AppStream
texlive-hyperref.noarch                    7:20180414-14.el8          @AppStream
texlive-hyph-utf8.noarch                   7:20180414-14.el8          @AppStream
texlive-hyphen-base.noarch                 7:20180414-14.el8          @AppStream
texlive-ifetex.noarch                      7:20180414-14.el8          @AppStream
texlive-ifluatex.noarch                    7:20180414-14.el8          @AppStream
texlive-ifxetex.noarch                     7:20180414-14.el8          @AppStream
texlive-index.noarch                       7:20180414-14.el8          @AppStream
texlive-kastrup.noarch                     7:20180414-14.el8          @AppStream
texlive-knuth-lib.noarch                   7:20180414-14.el8          @AppStream
texlive-knuth-local.noarch                 7:20180414-14.el8          @AppStream
texlive-koma-script.noarch                 7:20180414-14.el8          @AppStream
texlive-kpathsea.x86_64                    7:20180414-14.el8          @AppStream
texlive-l3kernel.noarch                    7:20180414-14.el8          @AppStream
texlive-l3packages.noarch                  7:20180414-14.el8          @AppStream
texlive-latex.noarch                       7:20180414-14.el8          @AppStream
texlive-latex-fonts.noarch                 7:20180414-14.el8          @AppStream
texlive-latexconfig.noarch                 7:20180414-14.el8          @AppStream
texlive-lib.x86_64                         7:20180414-14.el8          @AppStream
texlive-listings.noarch                    7:20180414-14.el8          @AppStream
texlive-lm.noarch                          7:20180414-14.el8          @AppStream
texlive-lm-math.noarch                     7:20180414-14.el8          @AppStream
texlive-lua-alt-getopt.noarch              7:20180414-14.el8          @AppStream
texlive-lualatex-math.noarch               7:20180414-14.el8          @AppStream
texlive-lualibs.noarch                     7:20180414-14.el8          @AppStream
texlive-luaotfload.noarch                  7:20180414-14.el8          @AppStream
texlive-luatex.x86_64                      7:20180414-14.el8          @AppStream
texlive-luatexbase.noarch                  7:20180414-14.el8          @AppStream
texlive-makeindex.x86_64                   7:20180414-14.el8          @AppStream
texlive-manfnt-font.noarch                 7:20180414-14.el8          @AppStream
texlive-marginnote.noarch                  7:20180414-14.el8          @AppStream
texlive-marvosym.noarch                    7:20180414-14.el8          @AppStream
texlive-mathpazo.noarch                    7:20180414-14.el8          @AppStream
texlive-memoir.noarch                      7:20180414-14.el8          @AppStream
texlive-metafont.x86_64                    7:20180414-14.el8          @AppStream
texlive-mflogo.noarch                      7:20180414-14.el8          @AppStream
texlive-mflogo-font.noarch                 7:20180414-14.el8          @AppStream
texlive-mfware.x86_64                      7:20180414-14.el8          @AppStream
texlive-mparhack.noarch                    7:20180414-14.el8          @AppStream
texlive-ms.noarch                          7:20180414-14.el8          @AppStream
texlive-multido.noarch                     7:20180414-14.el8          @AppStream
texlive-ncntrsbk.noarch                    7:20180414-14.el8          @AppStream
texlive-oberdiek.noarch                    7:20180414-14.el8          @AppStream
texlive-palatino.noarch                    7:20180414-14.el8          @AppStream
texlive-paralist.noarch                    7:20180414-14.el8          @AppStream
texlive-parallel.noarch                    7:20180414-14.el8          @AppStream
texlive-pdftex.x86_64                      7:20180414-14.el8          @AppStream
texlive-pgf.noarch                         7:20180414-14.el8          @AppStream
texlive-plain.noarch                       7:20180414-14.el8          @AppStream
texlive-psnfss.noarch                      7:20180414-14.el8          @AppStream
texlive-pst-3d.noarch                      7:20180414-14.el8          @AppStream
texlive-pst-coil.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-eps.noarch                     7:20180414-14.el8          @AppStream
texlive-pst-fill.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-grad.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-math.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-node.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-plot.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-text.noarch                    7:20180414-14.el8          @AppStream
texlive-pst-tree.noarch                    7:20180414-14.el8          @AppStream
texlive-pstricks.noarch                    7:20180414-14.el8          @AppStream
texlive-pstricks-add.noarch                7:20180414-14.el8          @AppStream
texlive-pxfonts.noarch                     7:20180414-14.el8          @AppStream
texlive-qstest.noarch                      7:20180414-14.el8          @AppStream
texlive-rsfs.noarch                        7:20180414-14.el8          @AppStream
texlive-sauerj.noarch                      7:20180414-14.el8          @AppStream
texlive-setspace.noarch                    7:20180414-14.el8          @AppStream
texlive-showexpl.noarch                    7:20180414-14.el8          @AppStream
texlive-soul.noarch                        7:20180414-14.el8          @AppStream
texlive-subfig.noarch                      7:20180414-14.el8          @AppStream
texlive-symbol.noarch                      7:20180414-14.el8          @AppStream
texlive-tetex.noarch                       7:20180414-14.el8          @AppStream
texlive-tex.x86_64                         7:20180414-14.el8          @AppStream
texlive-tex-gyre.noarch                    7:20180414-14.el8          @AppStream
texlive-tex-gyre-math.noarch               7:20180414-14.el8          @AppStream
texlive-tex-ini-files.noarch               7:20180414-14.el8          @AppStream
texlive-texconfig.noarch                   7:20180414-14.el8          @AppStream
texlive-texlive-common-doc.noarch          7:20180414-14.el8          @AppStream
texlive-texlive-docindex.noarch            7:20180414-14.el8          @AppStream
texlive-texlive-en.noarch                  7:20180414-14.el8          @AppStream
texlive-texlive-msg-translations.noarch    7:20180414-14.el8          @AppStream
texlive-texlive-scripts.noarch             7:20180414-14.el8          @AppStream
texlive-texlive.infra.noarch               7:20180414-14.el8          @AppStream
texlive-thumbpdf.noarch                    7:20180414-14.el8          @AppStream
texlive-times.noarch                       7:20180414-14.el8          @AppStream
texlive-tipa.noarch                        7:20180414-14.el8          @AppStream
texlive-tools.noarch                       7:20180414-14.el8          @AppStream
texlive-txfonts.noarch                     7:20180414-14.el8          @AppStream
texlive-underscore.noarch                  7:20180414-14.el8          @AppStream
texlive-unicode-data.noarch                7:20180414-14.el8          @AppStream
texlive-unicode-math.noarch                7:20180414-14.el8          @AppStream
texlive-updmap-map.noarch                  7:20180414-14.el8          @AppStream
texlive-url.noarch                         7:20180414-14.el8          @AppStream
texlive-utopia.noarch                      7:20180414-14.el8          @AppStream
texlive-varwidth.noarch                    7:20180414-14.el8          @AppStream
texlive-wasy.noarch                        7:20180414-14.el8          @AppStream
texlive-wasy2-ps.noarch                    7:20180414-14.el8          @AppStream
texlive-wasysym.noarch                     7:20180414-14.el8          @AppStream
texlive-xcolor.noarch                      7:20180414-14.el8          @AppStream
texlive-xdvi.x86_64                        7:20180414-14.el8          @AppStream
texlive-xetex.x86_64                       7:20180414-14.el8          @AppStream
texlive-xetexconfig.noarch                 7:20180414-14.el8          @AppStream
texlive-xkeyval.noarch                     7:20180414-14.el8          @AppStream
texlive-xunicode.noarch                    7:20180414-14.el8          @AppStream
texlive-zapfchan.noarch                    7:20180414-14.el8          @AppStream
texlive-zapfding.noarch                    7:20180414-14.el8          @AppStream
```

**Comment by martindholmes** [comment] 2020-07-23 04:53
@wobweger I don't understand what babel and reledmac have to do with the TEI Stylesheets. Is this a TEI Stylesheets issue, or is it just a question about how to get LaTeX working on your computer?

**Comment by wobweger** [comment] 2020-07-23 05:10
I'm actually clue less, might be simple a LaTeX installation problem, but it comes from official centOS repositories, so I assume they are supposed to work.

**Comment by martindholmes** [comment] 2020-07-23 15:47
@wobweger I don't actually see how this has anything to do with the TEI. I think you need to get some CentOS support. Unless there's an actual question about our stylesheets, I think this ticket should be closed. @peterstadler what do you think?

**Comment by peterstadler** [comment] 2020-07-31 08:57
Installing all the dependencies for all the various TEI transformations is not a simple task and I agree that the build instructions might be out of date. Yet, we provide a ready made [Docker image](https://hub.docker.com/r/teic/jenkins) which should provide you with all the necessary stuff to run all these transformations "out of the box" (especially see section "[Usage of the Docker image without the Jenkins server](https://github.com/teic/jenkins#usage-of-the-docker-image-without-the-jenkins-server)"). The respective [Dockerfile](https://github.com/TEIC/Jenkins/blob/dev/Dockerfile) documents all the needed packages for a Debian based system and might also provide some hints for your setup. 

@wobweger is the Docker image an option?

**Comment by wobweger** [comment] 2020-07-31 10:40
@peterstadler , thx, 
sure, so TEI provide an unexpected opportunity to get familiar with dockers, which I managed to avoid up to now.
Getting LaTeX; 3 I think;  running on my favored OS is going to improve my connectome significantly, :smile: , I hope.

**Comment by peterstadler** [comment] 2020-07-31 11:04
Yes, it seems you're not far from your goal and there's just that little LaTeX issue … (famous last words ;)
… so Docker might be overkill if you're not yet familiar with it.

@wobweger do you think we might close that issue if there's nothing TEI related left?

**Comment by wobweger** [comment] 2020-07-31 11:08
fine by me
many thinks for reading and engaging to all, :smile:

**Closed** 2020-07-31 11:09 UTC
Labels: Status: Needs Discussion, TEI: Build Process
