### ISSUE TITLE
create <schemaRef> element to give pointing to ODD.

### ISSUE THREAD

**Issue by TEITechnicalCouncil** [TEIC/TEI#564] opened 2015-06-12 12:01 UTC
for the sake of explicitly identifying the encoding methodology with the immediate practical application of having oxygen recognize various classes tei documents and assigning validation and transformation scenarios accordingly

eg.
`<editorialDecl methodology="teisimple”>`

other possible values: "teilite", "jtei"

Original comment by: @tuurma

**Comment by stefaniegehrke** [comment] 2015-10-26 13:10
perhaps encodingDesc would be a better place to address this ?

**Comment by lb42** [comment] 2015-10-26 13:13
Or use @type on <TEI>? or something else?

**Comment by martindholmes** [comment] 2015-10-26 13:20
Council 2015-10-26: SB suggests @odd (or @customization) on TEI, with either pointers to ODD files or a set of suggested values including tei:simple, tei:jtei etc.

**Comment by peterstadler** [comment] 2015-10-26 13:26
please have a look at http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TD-LinkingSchemas, as well and see whether it needs adjustments after your changes.

**Comment by jamescummings** [comment] 2016-01-04 17:22
Finally looking at this.  Since marked green I guess at the face to face we decided to go ahead with a new attribute on the TEI element called 'odd' or 'customization' giving one or more URI that point to an ODD files with some suggested private URI options of tei:simple, tei:jtei, tei:lite, tei:all?  I favour 'odd' or 'ODD' personally. Does anyone remember what the consensus was if we had one? 

Options:
1) odd
2) ODD
3) customization

**Comment by raffazizzi** [comment] 2016-01-04 18:16
I remember a debate between `@odd` (but we didn't discuss capitalization) and `@customization`, with maybe a shy majority towards `@odd`?

**Comment by jamescummings** [comment] 2016-02-24 11:18
Were there any other comments on this before I go forward with `@odd` as data.pointer?

**Comment by lb42** [comment] 2016-02-24 11:23
Are we going to deprecate &lt;schemaSpec> as child of &lt;encodingDesc> too? Or provide guidance on how the two methods coexist? (and I still think this is a daft idea)

**Comment by jamescummings** [comment] 2016-02-24 11:25
I don't think this issue should include that decision -- I think it is causing no harm. In adding a tiny bit of prose, I would assume that if both exist the one provided in the schemaSpec should have priority.  Is that what makes most sense?

**Comment by martindholmes** [comment] 2016-02-24 13:43
I like the ability to embed an ODD in the file itself (although I've never actually used it). A local schemaSpec should have priority over a linked one. Perhaps Schematron should prevent you from using both?

**Comment by lb42** [comment] 2016-02-24 16:15
Or perhaps we should invent a new element &lt;schemaRef> to point to an ODD, and then say you can have either &lt;schemaRef> or &lt;schemaSpec> inside the encoding desc? A lot cleaner and clearer than yet another arbitrary attribute methinks.

**Comment by laurentromary** [comment] 2016-02-24 16:16
This is certainly the way to go.

**Comment by jamescummings** [comment] 2016-02-24 16:30
Are we then saying we should have a <schemaRef/> element instead of an `@odd` attribute.  I get that is better for controlling the content model, but would need further discussion, no? We'd already decided on the latter so if we invented the former instead I think I'd like more comment from Council. Perhaps I should re-re-raise it on the mailing list.

**Comment by bansp** [comment] 2016-02-24 17:59
My first question upon seeing an attribute with a value such as 'tei:simple' or 'tei:jtei' would be "errm, which version?" And that would lead either to an attribute-internal grammar for parsing the value, or to yet another attribute. Or to an answer that some dedicated machinery would take care of deciphering the version information, to which my reply would be that in such a case, no special attribute is needed in the first place, perhaps (because if that dedicated machinery can decipher version information, it should also be able to decipher flavour information).
I like Lou's suggestion, though. It seems both elegant and powerful.

**Comment by tuurma** [comment] 2016-02-25 10:09
I like Lou's `<schemaRef>/<schemaSpec>` suggestion for the purpose of linking to a schema but it doesn't solve the use case that prompted this request in the first place. Which was to have means to explicitly declare a flavor (or flavors, plural) of TEI that a document follows. Reason to have this information was to enable editors, such as oXygen, differentiate the framework to apply for a given document.
I agree with the criticism that this is providing almost vendor-specific information and thus can be frowned upon, on the other hand 
1. oXygen users are a large portion of TEI users, 
1. workflows based on other software would need this information as well, one way or other and 
1. I believe it is of value to a human to be able to see quickly that 'this documents follows tei-lite (or tei-simple, or epidoc)' without knowing what particular customizations of those schemas that would be, as opposed to having a pointer to said customization that is nevertheless very hard to interpret.

If we could perhaps have the cake and eat it too, allow for an attribute on TEI element for this rough classification and `<schemaRef>/<schemaSpec>` for precise linking?

**Comment by lb42** [comment] 2016-02-25 10:23
If all you want is some way of quickly indicating roughly what flavour of TEI some document uses, surely @type is enough? Cf issue #1353 which is slated for implementation rsn.

**Comment by tuurma** [comment] 2016-02-25 10:41
@type is enough for internal project use, but if we want to make general recommendations for people where to state the general methodology they are following, pointing to a very general attribute like @type is not optimal I'd think?
Secondly @type suggests that we are classifying source documents (at least this is how I read #1353), while proposed @odd attribute is meant to classify encoding methodologies. Imagining the case where one would like to have both document and odd classifications, should one bag those in the same @type attribute? Feels clumsy.

**Comment by lb42** [comment] 2016-02-25 10:51
I think your distinctions don't really hold up. Suppose I am doing a project on how people use TEI Simple and amass a corpus of allegedly simple-conformant documents. Then my @type="simple" is both document and odd classification. And if you want to distinguish the two, use @type and @subtype. I really don't see any need to complicate this matter with a new attribute -- as you said several times, it's only intended to give a broadbrush characterisation of the source document, and it's only needed as an attribute on &lt;TEI> because of processing limitations of oXygen. In fact, I am now wondering why we don't recognize that fact and instead recommend use of a PI to signal that something has some particular TEI flavour.

**Comment by tuurma** [comment] 2016-02-25 10:58
I was thinking document type: letters, odd: simple, or document type: article, odd: jtei. I believe these are disparate classifications and not subtypes in any sense.

As for placement: I do agree putting stuff on TEI is not necessarily the most logical and the initial request was putting it on editorialDecl. It is very convenient though, even if not crucial as Alex Jitianu and I put together a little bit for oXygen to circumnavigate it's limitations here.

**Comment by lb42** [comment] 2016-02-25 11:04
Well, let us not quarrel about whether to call something  a "classification or a "subtype" :-) I am just saying you could do @type="article" @subtype="simple" (or the other way round) and get what you need.  The essential point is that this isn't a pointer to a specific instance of the ODD (that's what schemaRef would be if we had it)  but a vague characterisation of the document instance.

**Comment by laurentromary** [comment] 2016-02-25 11:09
I would suggest to have both:
- introduce schemaRef
- allow it to have either a reference to a generic TEI type (@type, etc.) or a @source to the associated ODD
Does this make sense?

**Comment by lb42** [comment] 2016-02-25 11:14
Laurent, that won't satisfy Magda's/oXygen's desire to have an attribute on the root element to tell it which framework to load

**Comment by tuurma** [comment] 2016-02-25 11:28
Let me repeat: putting the attribute on TEI element is *convenient* but not crucial. This is also a maintenance question if we want to provide specialized TEI frameworks (TEI Simple one exists already, so this is not entirely academical question).

As for @laurentromary's suggestion, @source makes perfect sense here and I'm fully supportive of the idea of introducing schemaRef. TEI @type though allows for a single value only afair? This is yet another reason why I'm unhappy with @type-based solutions. It is possible that a project follows, say tei-simple (for tagset choices) but also jtei at the same time.

**Comment by lb42** [comment] 2016-02-25 11:35
"It is possible that a project follows, say tei-simple (for tagset choices) but also jtei at the same time." The fact that this is is possible -- that a document can be valid against multiple schemas -- is yet another reason why this proposal makes me uneasy. All TEI conformant documents are (potentially) valid against many many schemas, both existing and as yet unformed.

**Comment by tuurma** [comment] 2016-02-25 11:39
Sure, though main concern here for me is editors declaring that their *intention* was to follow such-and-such policies and thus to be valid against corresponding schemas, not enumerating all schemas (including not yet existing) that document is valid against.

**Comment by tuurma** [comment] 2016-02-25 11:43
Which make me think: basically a namespace does it, perhaps just adding more namespaces to the document says what needs saying? What do you think?

**Comment by bansp** [comment] 2016-02-25 11:43
As Magda noted, part of the issue is a split between expressing an intention and stating a fact.
I interpret the schemaRef idea as a statement of fact. Statement of intention could be best expressed, it seems, as a PI.

**Comment by lb42** [comment] 2016-02-25 11:44
So we want to make it possible to say "this document is a Simple flavour document in which we have also applied the input constraints of jTEI" ? This is getting a bit fanciful... but if it's a statement of intention for the project, then it belongs in projectDesc !

**Comment by lb42** [comment] 2016-02-25 11:45
(and I don't see what the namespace issue has to do with it. all of these docs must be in the TEI namespace)

**Comment by tuurma** [comment] 2016-02-25 11:46
Yes, but they could potentially be also in tei-simple namespace at the same time.

**Comment by lb42** [comment] 2016-02-25 12:01
I don't think you can have more than one default namespace! So you could define
<simple:TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:simple="whatever"> but then your document isn't TEI conformant any more. If you care.

**Comment by tuurma** [comment] 2016-02-25 12:15
You are right, I was thinking something like this:
`<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:simple="whatever">` but then it's not the default one.

**Comment by bansp** [comment] 2016-02-25 12:39
May I humbly repeat at this point (after Lou, in fact): PI?
It is at the root, and the general PI semantics includes statements of intention.
And apart from this statement of intention, specRef (the way Lou proposed and with Laurent's additions) would be a cool way to state facts.

**Comment by raffazizzi** [comment] 2016-02-25 12:50
If we're looking for a way of indicating in a human-and-machine-readable way the "flavour" of TEI, don't we already have `schemaSpec/@ident`? (e.g. it's ident="teisimple" in teisimple.odd).

If we implement @lb42's suggestion for referring the ODD directly, that information will be available by following the link.

If we must replicate it in the TEI header somewhere, it should at the very least match with the intended `schemaSpec/@ident`, but I'm not sure how we could enforce that.

**Comment by ebeshero** [comment] 2016-02-25 12:55
I like Raff's suggestion here and the others, keeping this info in schemaSpec. But I am trying without success so far to find out what Lou and Piotr are referring to by Pl?

Elisa


Typeset by hand on my iPad

**Comment by hcayless** [comment] 2016-02-25 12:56
Processing Instruction. something like <?tei-flavor simple?>.

**Comment by jamescummings** [comment] 2016-02-25 13:01
Switching back to Needs Discussion since clearly all these conflicting ideas means I don't have a clear mandate to go and do X.

**Comment by ebeshero** [comment] 2016-02-25 13:05
Ahh, of course! Thanks. Does the use of PI replicate our past practice? The human-readable stuff seems like it would belong in encodingDesc...

Elisa
Typeset by hand on my iPad

**Comment by hcayless** [comment] 2016-02-25 13:44
PIs are something we've used for other stuff from time to time. I guess the
objection to a PI is that it's not quite a TEI thing, so maybe a bit
obscure for users? Whereas an attribute on the TEI element is something any
TEI encoder could get their head around easily.

**Comment by tuurma** [comment] 2016-03-31 18:13
Let's raise the subject once again to arrive at a decision...

**Comment by lb42** [comment] 2016-03-31 18:37
If the purpose is to tell oxygen which framework to load, then a pi is the way to do it

**Comment by jamescummings** [comment] 2016-04-01 10:27
I disagree that the purpose is to tell oxygen which framework to load. That is a beneficial side effect. The real purpose is to document for long-term preservation what ODD(s?) you were using to validate this document against. That is useful for alll sorts of reasons and is document metadata, not a processing instruction.  It is just it can _also_ be used for those wanting to do different forms of processing based on what ODD was in play.  But I would contend that the important use is for documentation but that we might as well do it in a way to help those who do want to process it.

**Comment by lb42** [comment] 2016-04-01 10:36
Well, clearly we need to decide what the object of this proposal is. If it's not a processing-related directive,but a question of documenting the ODD (or ODDs) from which a schema able to validate the doc instance may be generated, then I revive my suggestion of a new &lt;schemaRef> element with attributes @type (for vague categorisation) and @source (to indicate a specific ODD source)

**Comment by jamescummings** [comment] 2016-04-01 10:38
That seems sensible to me (as long as schemaRef is repeatable).

**Comment by martindholmes** [comment] 2016-04-01 15:53
James said an interesting thing there: " what ODD(s?) you were using to validate this document against". Of course, you can't validate documents against an ODD, only against schemas generated from it; and it's perfectly conceivable that you could validate your documents against one kind of schema generated from the ODD, and yet find that they were invalid against another kind of schema from the same ODD, because the ODD contains a constraint which is supported in one schema language but not in the other. So the notion of validating against an ODD is problematic, although interesting. Perhaps it means validating against every kind of schema generatable from the ODD.

**Comment by raffazizzi** [comment] 2016-04-01 16:11
I also like `<schemaRef>`, where `@source` provides all that is needed. I wish there also was an easy way to have something matching the `@ident` on a `<schemaSpec>` - I would certainly strive to do that in my TEI, maybe with `@type`.

**Comment by jamescummings** [comment] 2016-04-01 16:13
@martindholmes: Ok, yes, that was shorthand in the way most users use and think of ODDs simply as a simple customisation used to generate a schema.  I mean "Which ODD(s?) you were using to document the customisation, from which you may also have generated one or more schemas which you validated this document instance against at various points in your work flow".

The reason I want schemaRef to be repeatable is precisely so that people can put in multiple ODDs where their workflow uses them (which is something I've always suggested).

@raffazizzi good point.

**Comment by jamescummings** [comment] 2016-04-27 19:01
Council subgroup suggest `<schemaRef url="">`; JC agrees and will implement. Making green.

**Comment by jamescummings** [comment] 2016-04-27 19:31
Council suggests `@key (required)` and `@source` (optional)

**Comment by jeffreycwitt** [comment] 2016-06-21 13:09
After reading this thread, I'm very eager to use the proposed <schemaRef> element, but it is still unclear to me where the TEI council is recommending this element be placed in the TEI Header. 

Placing it as a child of the `<encodingDesc>` seems to make the most sense to me. Any help is appreciated.

**Comment by jamescummings** [comment] 2016-06-23 14:30
Hi @jeffreycwitt,

Yes, encodingDesc was precise where I was thinking it should go.  It should be in the dev version of the TEI Guidelines in the next few weeks. (It is slowly creeping up my to do list.)

**Comment by bansp** [comment] 2016-07-13 12:54
The ticket referenced above, #1483 , states some issues surrounding the TEI media type ("MIME type") and its potential extensions. An offshoot of that might be relevant for partial achievement of Magda's goal that motivated this very ticket, namely a way to detect or guess the TEI flavour.
If a media type parameter `format-variant` is defined for TEI Simple and other relevant flavours, and if it is tied to a file extension, then oXygen and other tools will be able to categorize the given file properly for the purpose of processing. Note that this is not a content-sniffing solution that Magda has asked for. But it's a solution. It is not in conflict with content-sniffing and it would be in line with what has been adopted elsewhere (namely, CLARIN) for the purpose of content detection (except there it's more about HTTP headers and web services). 
The downside is that it needs a specific file extension, and not everyone would be happy about ".simple" or something like that. Let me repeat however that defining a `format-variant` opens an _option_ rather than a _requirement_. It doesn't force new file extensions on you, it just makes it possible to use them (more) meaningfully.
That `format-variant` would/should still be reflected minimally in the ODD (and in my speculations I currently rather heavily lean towards reflecting it in the header of the specific instance as well). This would open the way for content-sniffing the way Magda wanted it. There are still some wrinkles to be ironed out concerning the difference between statements of intention and statements of fact (mentioned above).

**Comment by tuurma** [comment] 2016-11-17 14:39
settling this is required for having sensible framework for oXygen

**Comment by jamescummings** [comment] 2016-11-25 21:29
Adding as part of https://github.com/TEIC/TEI/commit/193ab2409ddff1b59ed4f845d4d7c12b7fe7335a which will break build but gets an initial spec file in. I'll add prose description a bit later once we test it.

**Comment by jamescummings** [comment] 2016-11-28 15:15
Added some prose to describe `<schemaRef>` in https://github.com/TEIC/TEI/commit/c38aaf2abfbb2ed8404aec21f4fa665c864aa28e

**Comment by jamescummings** [comment] 2016-11-28 21:27
Since this seems to all be fine in jenkins I'm closing.

**Closed by jamescummings** 2016-11-28 21:27 UTC
Labels: sf-automigrated, Status: Go, TEI: Schema, Type: FeatureRequest

**Comment by jeffreycwitt** [comment] 2016-12-05 20:56
@jamescummings any ideas when I can expect the next release build containing the results of this [c38aaf2](https://github.com/TEIC/TEI/commit/c38aaf2abfbb2ed8404aec21f4fa665c864aa28e).

I'd like to update my ODD schema to point at a build that contains the results of this update.

for example:
<schemaSpec ident="lombardpress-schema" start="TEI"
                  source="http://www.tei-c.org/Vault/P5/**3.0.1**/xml/tei/odd/p5subset.xml">

Oh, and thanks for your work on this by the way. Much appreciated!!

**Comment by martindholmes** [comment] 2016-12-05 21:06
You can build a schema against the development version of TEI by pointing here:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/odd/p5subset.xml

But bear in mind that the file changes several times a day and may occasionally be broken. When you're doing this, though, it's best to use the Stylesheets development version for your XSL source:

http://teijenkins.hcmc.uvic.ca/job/Stylesheets-dev/lastSuccessfulBuild/artifact/dist/xml/tei/stylesheet/

because they're developed in tandem. If you want to test out a new feature, this is a useful way to do it, and you can report any bugs.

**Comment by jeffreycwitt** [comment] 2016-12-05 21:19
@martindholmes thanks very much.
jw

**Comment by jamescummings** [comment] 2016-12-06 12:35
Otherwise we're currently planning a release (assuming we can fix any other release-blocking bugs) on 15 Dec.
