### ISSUE TITLE
xsl:* (or other non-sch:*) not allowed within constraintSpec

### ISSUE THREAD

**Issue by ebeshero** [TEIC/TEI#1607] opened 2017-03-12 07:08 UTC
Some Schematron rules require the use of `<xsl:variable>` when particular functionality is missing from a Schematron variable. One example involves testing whether Roman numerals in one element match a numerical value in a nearby attribute (for which one might wish to define an `<xsl:variable>` to convert the value of the number into a Roman numeral using `@format="I"`, which is unavailable in the Schematron variable). 

Schematron permits the embedding of xsl: variables in its syntax in a standalone file. However, if one attempts to write this in an ODD constraintSpec, it's flagged as an error because the descendant elements of `<constraint>` must all be defined in the sch: (Schematron) namespace. If one ignores the tei_odds schema error, one can output a Relax NG Schema in XML syntax that holds the Schematron rule with its variable, but it's apparently not fully functional in the Relax NG context: Schematron contexts and variables don't pass into the xsl:variable. 

I've made this work in my project by compiling the ODD schema without the rule with the xsl:variable, and just storing it in a separate Schematron file that I associate with the files that require Roman numeral checking. But it would be nice to see full functionality of Schematron in ODD, including embedded xsl that might reasonably be evoked in a Schematron file.

**Comment by martindholmes** [comment] 2017-03-12 17:37
Can you not use `<let>` for this?

https://www.xml.com/pub/a/2003/11/12/schematron.html#Variables_using_let

**Comment by ebeshero** [comment] 2017-03-12 17:46
@martindholmes Alas, not that I can see. The Schematron `<let>` variables don't permit the reformatting of numerals, (or dates or times, for that matter). For that I needed to embed an XSL variable with an `@format` attribute. The solution took me a while to research, but the code itself is pretty straightforward--just embedding an xsl:variable in the pattern to handle the conversion, and then call it in the sch:assert or report test. That transference of variables is what's not happening in the ODD context.

**Comment by ebeshero** [comment] 2017-03-12 18:09
@martindholmes OK--for dates, there is a handy XPath function for conversions that would work in sch:let: http://www.sixtree.com.au/articles/2013/formatting-dates-and-times-using-xslt-2.0-and-xpath/

I see we also have a format-integer() function in XPath 3.0, which works similarly on picture strings and patterns.  But  the xsl:variable solution is a simpler (less verbose) implementation on reading numbers to Roman numerals (not confined to date patterns). And it's tidy--a convenient functionality that works in standalone Schematron. So that's my question here--why can't we use xsl: variable functionality in the ODD environment just as we can in native Schematron?

**Comment by martindholmes** [comment] 2017-03-12 22:51
I don't see any objection to allowing elements in the XSLT namespace into constraintSpec, and your use-case seems compelling.

**Comment by rvdb** [comment] 2017-03-13 09:57
By coincidence, last Friday I had started drafting an issue on exactly this same problem (tei_odds being too strict about xsl descendants of `<constraint>`), while (in some respect) the stylesheets are more permissive and are copying some XSLT elements to the generated schema. 

I was holding back to post the issue here, since it involves multiple TEI repos (TEI and Stylesheets, to tackle some XSLT elements that are not being copied properly, while they seem perfectly valid in the generated schema). While experimenting a bit in order to get a good test case, I had noticed how all XSLT elements I drop in Schematron tend to be accepted and executed by the validation engine in Oxygen. Yet, I'm not sure at all which XSLT elements are really allowed, and if the (validation framework in) Oxygen might be too permissive, so I'm trying to clarify this first. I've posted this on the Oxygen forum (https://www.oxygenxml.com/forum/topic14236.html), hoping to get feedback there.

**Comment by rvdb** [comment] 2017-03-13 16:12
Ok, it seems that a) while XSLT support inside Schematron is implementation-dependent, b) the Schematron “Skeleton” Implementation that is used by Oxygen allows for XSLT. In his [answer to my question](https://www.oxygenxml.com/forum/topic14236.html#p41973) Octavian mentions this implementation as the reference implementation, which seems to me a further argument for allowing xsl:* elements inside `<constraint>`, and relaxing the Schematron check in the files that are being generated at http://jenkins.tei-c.org/job/oxygen-tei-bleeding/ws/oxygen-tei/frameworks/tei/xml/tei/custom/schema/relaxng/tei_odds.rnc and http://jenkins.tei-c.org/job/oxygen-tei-bleeding/ws/oxygen-tei/frameworks/tei/xml/tei/custom/schema/relaxng/tei_odds.rng (I haven't found a source file containing this check, though, so I don't know where it is coming from).

**Comment by martindholmes** [comment] 2017-03-13 16:15
Annex H of the Schematron 2016 standard:

http://standards.iso.org/ittf/PubliclyAvailableStandards/c055982_ISO_IEC_19757-3_2016.zip

should tell us what aspects of XPath and XSLT2 are formally supported by Schematron. It says:

> The xslt2 query language binding allows schemas implemented using XSLT2.

I'm not sure whether this means that anything and everything from XSLT2 is allowed in a Schematron rule if the xslt2 query language binding is invoked. It also says:

> —	 A Schematron let expression is treated as an XSLT2 variable. The XSLT2 $ delimiter signifies the use of a variables [sic] in an [sic] context expression, assertion test, name query, value-of query or let expression. The character not followed by the name of an in-scope variable shall be treated as a literal character.

It doesn't look very thoroughly proofed, but this suggests that sch:let and xsl:variable are equivalent, and therefore that you should be able to use xsl:variable.

If the standard permits it, and the most common implementations support it, then TEI should support it too.

**Comment by rvdb** [comment] 2017-03-13 16:22
Indeed, the implementation seems to allow far more XSLT constructs than are specified by the standard, and Octavian's answer on the Oxygen support forum seems to confirm this. I've created a [gist](https://gist.github.com/rvdb/ad2dc77bf5fc33b4e02cb3e415d19888) with some XSLT elements that are not mentioned in the standard, and this just seems to work.

So, the situation is indeed a bit hazy: the standard only lists a couple of XSLT elements (while not prohibiting others, though), while the implementation is much more permissive.

**Comment by rvdb** [comment] 2017-03-13 18:54
Also, I think it would make sense to allow nodes from the Schematron Quick Fix namespace (http://www.schematron-quickfix.com/validator/process) inside `<constraint>` as well.

**Comment by sydb** [comment] 2017-03-31 17:49
I have not read most of this ticket, but rather came across it while trying to do due diligence before creating a new one for a bug that Martin & I just discovered. In constraint.xml, the content model for `<constraint>` is declared as
~~~~~xml
    <alternate minOccurs="0" maxOccurs="unbounded">
      <textNode/>
      <anyElement require="http://purl.oclc.org/dsdl/schematron"/>
    </alternate>
~~~~~
which is, frankly, wrong. The content of `<constraint>` should just be `<anyElement>`. A user is free to express his or her constraint in any language she chooses, not just Schematron. (**If** the parent `<constraintSpec>` has a `@scheme` attribute of `"schematron"` (or, deprecated, `"isoschematron"`), **then** the content of `<constraint>` should be limited to Schematron, but that means just `<anyElement>` without the alternate `<textNode>`, as Schematron allows elements and attributes from any namespace.)

**Comment by martindholmes** [comment] 2018-02-14 16:26
I claim that if we add this line:

~~~~~
<ref name="anySchematron"/>
~~~~~

at line 133 of p5odds.odd, we should fix the problem. Any reason not to do this?

**Comment by sydb** [comment] 2018-02-15 00:56
Yes, I think that would solve this problem, and might be the appropriate thing to do for p5odds.odd. But overall I wonder …

a) Should be defining the content model of Schematron elements, or importing the Schematron schema? Interesting question: is there a Schematron schema that includes SQF? A quick search says yes, there is a schemas/ directory on the [SQF GitHub site](https://github.com/schematron-quickfix/sqf/tree/master/schemas). However, the schemas therein are XSD. However, the comment in the XSD says it was converting with `trang`. Where’s the source, and is it REALX NG?

b) Surely not **any** Schematron element is allowed inside any SQF element, right? But I am not sure how to read the error message I got from oXygen; it may imply exactly that:
> One of '{"http://purl.oclc.org/dsdl/schematron":value-of, "http://purl.oclc.org/dsdl/schematron":name, WC[""], WC[##other:"http://purl.oclc.org/dsdl/schematron",""]}' is expected.

I understand the first two expected thingies, but can someone explain that WC construct?

Also, the content of element `<content>` should not include `<ref name="anySchematron"/>`, I don’t think, as we do not use Schematron 1.x (only ISO Schematron) in the _Guidelines_ nowadays. I will consider that bit on me.

**Comment by sydb** [comment] 2018-02-15 01:02
OK. I’ve removed the extraneous Schematron 1.x bits from my local copy of p5odds.odd, but should I hold off on committing it until this problem is dealt with?

(BTW, I have not just systematically nuked all Schematron NSs and looked for errors, because I am guessing that some occurrences are legit, and there are lots to look through. Over 330 occurrences in over 125 files.

**Comment by martindholmes** [comment] 2018-02-15 04:44
@sydb If you agree with my fix, that's two voices, so how about rolling it in with your changes and seeing what happens?

**Comment by sydb** [comment] 2018-02-15 12:02
Done at 1925b03.

**Comment by rvdb** [comment] 2018-02-19 10:42
Great, so far so good for allowing SQF descendants of `<constraint>`; could http://www.w3.org/1999/XSL/Transform be added as an allowed namespace for `<constraint>` descendants as well, or does this need more discussion?

**Comment by martindholmes** [comment] 2018-02-19 16:10
I see no objection myself; it would be good to have example use-cases though.

**Comment by rvdb** [comment] 2018-02-19 16:50
One use-case could be the use of `<xsl:key>` in order to make more performant checks for e.g. `@xml:id` values. For example: https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_jtei.odd#L2149-L2152 could be rewritten as:

    
    <xsl:key name="idrefs" match="@target[starts-with(., '#')]" use="for $i in tokenize(., '\s+') return substring-after($i, '#')"/>
    <sch:assert test="key('idrefs', @xml:id)/parent::*[self::tei:ref][@type='bibl']">
      This bibliographic entry is an orphan: no ref[@type="bibl"] references to it occur in the text.
    </sch:assert>

The `<xsl:key>` element is copied without problems by the ODD2RelaxNG transformation, and the resulting RelaxNG schema works. In order to make this ODD pass validation, however, I guess:

- the XSL namespace should be added to the content model of `<constraint>` (https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/constraint.xml#L16)
- XSL elements will probably have to be added to the macro definition for `anyISOSchematron` (https://github.com/TEIC/TEI/blob/dev/P5/p5odds.odd#L90), though I'm not too sure what exactly should happen there (I don't know if XSL elements should be allowed inside SQF elements, for example)

I could just rework the jTEI ODD with some XSL elements (where it makes sense, of course), and see how it affects the build/validation process?

**Comment by martindholmes** [comment] 2018-02-19 17:19
That's a perfect example.

**Comment by rvdb** [comment] 2018-02-19 21:11
Ok, done in https://github.com/TEIC/TEI/pull/1742. Shall I leave additional changes in the ODD validation machinery to the experts?

**Comment by martindholmes** [comment] 2018-02-19 21:16
Someone from Council should OK the addition of the XSLT namespace elements, in case there's some issue I haven't thought of. We should hold off on committing the ODD changes till that's done, otherwise the ODD will be invalid.

**Comment by ebeshero** [comment] 2018-02-26 11:54
Council suggests we change the content of `<constraint>` thus (to remove `@require` from `<anyElement>` 

~~~~~xml
    <alternate minOccurs="0" maxOccurs="unbounded">
      <textNode/>
      <anyElement/>
    </alternate>
~~~~~

**Comment by sydb** [comment] 2018-04-20 23:39
Committed at 6c508bd.

I did get one weird message on my local build:
~~~~~
isoschematron:
     [echo] XSLT generate ISO schematron tei_jtei.isosch from compiled ODD 
     [xslt] Processing /Users/syd/Documents/TEI-GitHub/P5/Exemplars/tei_jtei.odd.processed to /Users/syd/Documents/TEI-GitHub/P5/Exemplars/tei_jtei.isosch
     [xslt] Loading stylesheet /Users/syd/Documents/Stylesheets/odds/extract-isosch.xsl
     [xslt] Processing /Users/syd/Documents/TEI-GitHub/P5/Exemplars/tei_jtei.isosch to /Users/syd/Documents/TEI-GitHub/P5/Exemplars/tei_jtei.xsl
     [xslt] Loading stylesheet /Users/syd/Documents/TEI-GitHub/P5/Utilities/iso_schematron_message_xslt2.xsl
     [xslt] Error: unrecognized element in ISO Schematron namespace: check spelling and capitalizationvalue-of
     [xslt] Error: unrecognized element in ISO Schematron namespace: check spelling and capitalizationvalue-of
~~~~~
but was not able to figure out what it’s talking about.

**Comment by rvdb** [comment] 2018-04-25 12:25
@sydb Great, I can confirm how this fixes validation of the jTEI ODD with XSLT elements inside `<constraintSpec>`. Ok to merge https://github.com/TEIC/TEI/pull/1742, then?

**Comment by rvdb** [comment] 2018-08-21 13:01
I've just realized my PR (https://github.com/TEIC/TEI/pull/1742) is still pending, awaiting resolution of this issue. Did @sydb 's commit (https://github.com/TEIC/TEI/commit/6c508bd50487e4501aa8aee68e0cdf39f7561977) solve this issue sufficiently (I think it does, by successfully allowing elements from other namespaces inside `<constraint>` in ODD files), or are there any problems left?

**Comment by sydb** [comment] 2018-08-21 13:26
Sorry! Just merged. I did not work through the logic completely, but on first glance seems perfectly fine. @rvdb may want to tweak some more per my comment on the pull request.

Does this mean we can close this ticket?

**Comment by martindholmes** [comment] 2018-08-29 23:52
The presence of xsl:key in tei_jtei.odd is still causing the P5-dev build to fail. More work needed here I think.

**Comment by sydb** [comment] 2018-08-31 14:45
Guess my thoughts, above, about doing the same in p5odds never made it in; done at #84e541c .

**Closed** 2018-09-07 06:34 UTC
Labels: Status: Go, Status: Needs Discussion, TEI: ODD, TEI: Schema, Type: Bug
